/**
 * Etiquetas de los campos de formulario, por clave de estado.
 *
 * Los módulos normativos construyen sus campos con helpers dinámicos —
 * `select("criticality", [...])`, `field("dueDate")` — donde el nombre del
 * campo solo existe como clave. Sin esta tabla ese control llega al usuario
 * sin nombre accesible.
 *
 * Es la misma tabla que usó el codemod que dio nombre a los 1.198 campos
 * heredados, extraída aquí para que el código nuevo no vuelva a divergir.
 */
const ETIQUETAS: Record<string, string> = {
  accessRole: "Rol de acceso",
  actionDescription: "Descripción de la acción",
  actionDueDate: "Vencimiento de la acción",
  actionPriority: "Prioridad de la acción",
  actionTitle: "Título de la acción",
  actionType: "Tipo de acción",
  activityType: "Tipo de actividad",
  address: "Dirección",
  affectedAreas: "Áreas afectadas",
  allegationType: "Tipo de denuncia",
  archiveMethodId: "Método de archivo",
  associateType: "Tipo de asociado",
  audience: "Audiencia",
  auditId: "Auditoría",
  auditeeIds: "Auditados",
  auditorExternal: "Auditor externo",
  auditorId: "Auditor",
  autonomy: "Autonomía",
  baseline: "Línea base",
  boundaries: "Límites",
  bump: "Incremento de versión",
  category: "Categoría",
  chairId: "Presidente",
  changeType: "Tipo de cambio",
  channel: "Canal",
  ciType: "Tipo de elemento de configuración",
  classification: "Clasificación",
  clauseCode: "Código de cláusula",
  clauseFilter: "Filtrar por cláusula",
  clauseId: "Cláusula",
  code: "Código",
  comment: "Comentario",
  commitmentType: "Tipo de compromiso",
  communicatedAt: "Fecha de comunicación",
  communicatedById: "Comunicado por",
  communication: "Comunicación",
  conclusion: "Conclusión",
  conditionOnReceipt: "Estado a la recepción",
  confidentiality: "Confidencialidad",
  conflictNature: "Naturaleza del conflicto",
  conflictType: "Tipo de conflicto",
  contactEmail: "Correo de contacto",
  contactName: "Nombre de contacto",
  contactPhone: "Teléfono de contacto",
  content: "Contenido",
  contextNotes: "Notas de contexto",
  controlArea: "Área de control",
  controlType: "Tipo de control",
  correctiveAction: "Acción correctiva",
  country: "País",
  countryRisk: "Riesgo país",
  courseId: "Curso",
  criteria: "Criterios",
  criticality: "Criticidad",
  csv: "Archivo CSV",
  ctrlStatus: "Estado del control",
  currentValue: "Valor actual",
  custodianId: "Custodio",
  customerName: "Cliente",
  date: "Fecha",
  decision: "Decisión",
  defaultDueDays: "Días de plazo por defecto",
  defaultValidityMonths: "Meses de validez por defecto",
  deliveryMode: "Modalidad",
  depType: "Tipo de dependencia",
  dependency: "Dependencia",
  description: "Descripción",
  designAdequate: "Diseño adecuado",
  detailNote: "Detalle",
  detectionSource: "Origen de la detección",
  direction: "Sentido",
  dispositionId: "Disposición",
  dueAt: "Fecha de vencimiento",
  dueDate: "Fecha de vencimiento",
  editScore: "Puntuación",
  editStatus: "Estado",
  effectiveness: "Eficacia",
  email: "Correo electrónico",
  emergencyType: "Tipo de emergencia",
  employees: "Empleados",
  endDate: "Fecha de fin",
  entryDate: "Fecha de entrada",
  environment: "Entorno",
  evaluatedAt: "Fecha de evaluación",
  evaluationFrequency: "Frecuencia de evaluación",
  evidenceFile: "Archivo de evidencia",
  evidenceId: "Evidencia",
  evidenceType: "Tipo de evidencia",
  evidenceUrl: "Enlace a la evidencia",
  exclusions: "Exclusiones",
  expected: "Resultado esperado",
  expiresAt: "Fecha de caducidad",
  externalAccount: "Cuenta externa",
  family: "Familia",
  file: "Archivo",
  findingId: "Hallazgo",
  firstName: "Nombre",
  folderFilter: "Filtrar por carpeta",
  formulaKind: "Tipo de fórmula",
  frequency: "Frecuencia",
  handlingInstructions: "Instrucciones de manipulación",
  hazardType: "Tipo de peligro",
  hiredAt: "Fecha de alta",
  identification: "Identificación",
  identificationMode: "Modo de identificación",
  impact: "Impacto",
  impactStatus: "Estado del impacto",
  implementationComments: "Comentarios de implantación",
  influence: "Influencia",
  inputs: "Entradas",
  ishikawaAnalysis: "Análisis de Ishikawa",
  issuedAt: "Fecha de emisión",
  itemDescription: "Descripción del artículo",
  kind: "Tipo",
  lastName: "Apellidos",
  legalBasis: "Base legal",
  lessons: "Lecciones aprendidas",
  lessonsLearned: "Lecciones aprendidas",
  level: "Nivel",
  levelFilter: "Filtrar por nivel",
  likelihood: "Probabilidad",
  locationId: "Ubicación",
  lotType: "Tipo de lote",
  materializationEvidence: "Evidencia de materialización",
  matrixEdition: "Edición de la matriz",
  method: "Método",
  monitoringFrequency: "Frecuencia de vigilancia",
  name: "Nombre",
  nature: "Naturaleza",
  needs: "Necesidades",
  nextReviewAt: "Próxima revisión",
  nextReviewDate: "Próxima revisión",
  nextReviewDue: "Próxima revisión",
  nonconformityId: "No conformidad",
  normalizationMethod: "Método de normalización",
  note: "Nota",
  notes: "Notas",
  objectives: "Objetivos",
  obligationType: "Tipo de obligación",
  observations: "Observaciones",
  operatingEffective: "Operación eficaz",
  operator: "Operador",
  origin: "Origen",
  outcome: "Resultado",
  outputs: "Salidas",
  ownerId: "Responsable",
  ownershipRole: "Rol de propiedad",
  packagingNote: "Nota de embalaje",
  parentId: "Elemento superior",
  participantIds: "Participantes",
  party: "Parte",
  performedAt: "Fecha de realización",
  periodEnd: "Fin del periodo",
  periodStart: "Inicio del periodo",
  personnelId: "Persona",
  plannedDate: "Fecha planificada",
  plannedEnd: "Fin planificado",
  plannedStart: "Inicio planificado",
  policy: "Política",
  positionId: "Puesto",
  presentedTo: "Presentado a",
  priority: "Prioridad",
  probability: "Probabilidad",
  processFilter: "Filtrar por proceso",
  processId: "Proceso",
  processLinkDraft: "Proceso vinculado",
  programId: "Programa",
  progress: "Progreso",
  provider: "Proveedor",
  providerType: "Tipo de proveedor",
  question: "Pregunta",
  reason: "Motivo",
  recallType: "Tipo de retirada",
  receivedAt: "Fecha de recepción",
  recordType: "Tipo de registro",
  recordTypeId: "Tipo de registro",
  recurrence: "Recurrencia",
  relationType: "Tipo de relación",
  reportType: "Tipo de informe",
  reputationalImpact: "Impacto reputacional",
  requirements: "Requisitos",
  residualScore: "Puntuación residual",
  resources: "Recursos",
  response: "Respuesta",
  responsibleApprovalId: "Responsable de aprobación",
  responsibleElaborationId: "Responsable de elaboración",
  responsibleId: "Responsable",
  result: "Resultado",
  retentionTimeId: "Tiempo de retención",
  review: "Revisión",
  reviewDate: "Fecha de revisión",
  reviewerId: "Revisor",
  riskLevel: "Nivel de riesgo",
  riskTier: "Nivel de riesgo",
  role: "Rol",
  rootCause: "Causa raíz",
  rootCauseMethod: "Método de causa raíz",
  scheduledDate: "Fecha prevista",
  scheduledFor: "Fecha prevista",
  scope: "Alcance",
  score: "Puntuación",
  sectorRisk: "Riesgo sectorial",
  serviceType: "Tipo de servicio",
  severity: "Severidad",
  source: "Fuente",
  sourceType: "Tipo de fuente",
  stageType: "Tipo de etapa",
  standardCode: "Código de norma",
  standards: "Normas",
  startDate: "Fecha de inicio",
  status: "Estado",
  statusFilter: "Filtrar por estado",
  stepType: "Tipo de paso",
  storageConditions: "Condiciones de almacenamiento",
  subject: "Asunto",
  summary: "Resumen",
  target: "Meta",
  targetDomain: "Dominio objetivo",
  targetType: "Tipo de objetivo",
  targetValue: "Valor objetivo",
  title: "Título",
  topic: "Tema",
  transactionType: "Tipo de transacción",
  treatment: "Tratamiento",
  type: "Tipo",
  typeFilter: "Filtrar por tipo",
  unit: "Unidad",
  urgency: "Urgencia",
  value: "Valor",
  valueProposition: "Propuesta de valor",
  variableType: "Tipo de variable",
  verifyStatus: "Estado de verificación",
  year: "Año",
  years: "Años",
};

/**
 * Etiqueta legible para una clave de campo.
 *
 * Devuelve `undefined` cuando la clave no está en la tabla: es preferible un
 * campo medible como pendiente a uno con una etiqueta inventada. Quien la
 * necesite debe añadir la entrada aquí.
 */
export function labelForKey(key: string): string | undefined {
  return ETIQUETAS[key];
}

/** Igual, pero cae en la propia clave para no dejar el control sin nombre. */
export function labelForKeyOrRaw(key: string): string {
  return ETIQUETAS[key] ?? key;
}
