import type { StandardPackInput } from "./pack-schema";

/**
 * ISO/IEC 42001:2023 — Sistema de Gestión de Inteligencia Artificial (SGIA).
 *
 * Only clause codes, structure and NormaFlow's OWN Spanish titles/summaries —
 * never the protected full text of the standard. Requirement ids resolve to the
 * stable `req-iso-42001-<code>` form via `requirementIdFor`.
 *
 * Incluye el Anexo A (controles del SGIA) porque es donde viven las exigencias
 * que el módulo automatiza: inventario, evaluación de impacto, datos, modelos,
 * supervisión humana, transparencia e incidentes.
 */
export const iso42001Pack: StandardPackInput = {
  code: "PACK_ISO_42001",
  name: "ISO/IEC 42001 — Inteligencia artificial",
  version: "2023.1",
  description: "Paquete normativo ISO/IEC 42001:2023 (Sistema de Gestión de Inteligencia Artificial).",
  requiredModules: [
    "gap", "documents", "audits", "nc", "capa", "indicators", "mgmt-review", "training", "suppliers", "risks", "aims",
  ],
  featureFlags: { aiManagement: true, humanReviewRule: true },
  editions: [
    {
      familyCode: "ISO_42001",
      familyName: "ISO/IEC 42001",
      category: "Inteligencia artificial",
      familyDescription: "Sistema de Gestión de Inteligencia Artificial",
      editionCode: "2023",
      name: "ISO/IEC 42001",
      version: "2023",
      year: 2023,
      description: "Sistema de Gestión de Inteligencia Artificial (SGIA)",
      catalogVersion: "2023.1",
      status: "ACTIVE",
      requirements: [
        { code: "4", title: "Contexto de la organización" },
        { code: "4.1", title: "Comprensión de la organización y de su contexto", parent: "4" },
        { code: "4.2", title: "Comprensión de las necesidades y expectativas de las partes interesadas", parent: "4", summary: "Incluye a las personas afectadas por los sistemas de IA, no solo a clientes y reguladores." },
        { code: "4.3", title: "Determinación del alcance del sistema de gestión de la IA", parent: "4" },
        { code: "4.4", title: "Sistema de gestión de la IA", parent: "4" },
        { code: "5", title: "Liderazgo" },
        { code: "5.1", title: "Liderazgo y compromiso", parent: "5" },
        { code: "5.2", title: "Política de IA", parent: "5", summary: "Política de uso responsable de la IA, usos prohibidos y principios asumidos." },
        { code: "5.3", title: "Roles, responsabilidades y autoridades", parent: "5", summary: "Propietario de cada sistema de IA y quién decide sobre sus salidas." },
        { code: "6", title: "Planificación" },
        { code: "6.1", title: "Acciones para abordar riesgos y oportunidades", parent: "6" },
        { code: "6.1.1", title: "Generalidades", parent: "6.1" },
        { code: "6.1.2", title: "Evaluación de riesgos de la IA", parent: "6.1", summary: "Valoración de riesgos por sistema: probabilidad, impacto, riesgo residual y aceptabilidad." },
        { code: "6.1.3", title: "Tratamiento de riesgos de la IA", parent: "6.1", summary: "Plan de tratamiento y aceptación formal del riesgo residual por una persona responsable." },
        { code: "6.1.4", title: "Evaluación del impacto de los sistemas de IA", parent: "6.1", summary: "Impacto sobre derechos, seguridad, privacidad, sesgo, transparencia, explicabilidad y supervisión humana." },
        { code: "6.2", title: "Objetivos de IA y planificación para lograrlos", parent: "6" },
        { code: "6.3", title: "Planificación de los cambios", parent: "6", summary: "Cambios de modelo, datos, prompts o alcance con análisis de impacto previo." },
        { code: "7", title: "Apoyo" },
        { code: "7.1", title: "Recursos", parent: "7" },
        { code: "7.2", title: "Competencia", parent: "7", summary: "Competencia de quienes supervisan, revisan y aprueban salidas de IA." },
        { code: "7.3", title: "Toma de conciencia", parent: "7" },
        { code: "7.4", title: "Comunicación", parent: "7" },
        { code: "7.5", title: "Información documentada", parent: "7" },
        { code: "8", title: "Operación" },
        { code: "8.1", title: "Planificación y control operacional", parent: "8" },
        { code: "8.2", title: "Evaluación de riesgos de la IA", parent: "8", summary: "Ejecución de la valoración de riesgos planificada." },
        { code: "8.3", title: "Tratamiento de riesgos de la IA", parent: "8" },
        { code: "8.4", title: "Evaluación del impacto de los sistemas de IA", parent: "8", summary: "Ejecución y aprobación humana de la evaluación de impacto." },
        { code: "9", title: "Evaluación del desempeño" },
        { code: "9.1", title: "Seguimiento, medición, análisis y evaluación", parent: "9", summary: "Monitoreo continuo en producción: desempeño, deriva, sesgo y tasa de anulación humana." },
        { code: "9.2", title: "Auditoría interna", parent: "9" },
        { code: "9.3", title: "Revisión por la dirección", parent: "9" },
        { code: "10", title: "Mejora" },
        { code: "10.1", title: "Mejora continua", parent: "10" },
        { code: "10.2", title: "No conformidad y acción correctiva", parent: "10" },

        // Anexo A — controles del SGIA.
        { code: "A", title: "Anexo A — Controles del sistema de gestión de IA" },
        { code: "A.2", title: "Políticas relacionadas con la IA", parent: "A" },
        { code: "A.2.2", title: "Política de IA", parent: "A.2" },
        { code: "A.2.3", title: "Alineación con otras políticas de la organización", parent: "A.2" },
        { code: "A.3", title: "Roles y responsabilidades internas", parent: "A" },
        { code: "A.3.2", title: "Roles y responsabilidades de la IA", parent: "A.3" },
        { code: "A.3.3", title: "Reporte de preocupaciones", parent: "A.3", summary: "Canal para plantear preocupaciones sobre un sistema de IA." },
        { code: "A.4", title: "Recursos para los sistemas de IA", parent: "A" },
        { code: "A.4.2", title: "Documentación de recursos", parent: "A.4" },
        { code: "A.4.3", title: "Recursos de datos", parent: "A.4" },
        { code: "A.4.4", title: "Recursos de herramientas", parent: "A.4" },
        { code: "A.4.5", title: "Recursos de sistema y computación", parent: "A.4" },
        { code: "A.4.6", title: "Recursos humanos", parent: "A.4" },
        { code: "A.5", title: "Evaluación del impacto de los sistemas de IA", parent: "A" },
        { code: "A.5.2", title: "Proceso de evaluación del impacto", parent: "A.5", summary: "Metodología de evaluación de impacto con dimensiones y severidades definidas." },
        { code: "A.5.3", title: "Documentación de la evaluación del impacto", parent: "A.5" },
        { code: "A.5.4", title: "Impacto sobre individuos y grupos", parent: "A.5" },
        { code: "A.5.5", title: "Impacto sobre la sociedad", parent: "A.5" },
        { code: "A.6", title: "Ciclo de vida del sistema de IA", parent: "A" },
        { code: "A.6.1", title: "Gestión responsable del desarrollo", parent: "A.6" },
        { code: "A.6.2", title: "Proceso de ciclo de vida", parent: "A.6", summary: "Del diseño al retiro, con puertas de aprobación humana antes de producción." },
        { code: "A.6.2.2", title: "Requisitos y especificación del sistema de IA", parent: "A.6.2" },
        { code: "A.6.2.3", title: "Diseño y desarrollo documentados", parent: "A.6.2" },
        { code: "A.6.2.4", title: "Verificación y validación del sistema de IA", parent: "A.6.2", summary: "Evaluación del modelo: desempeño, sesgo, robustez y explicabilidad." },
        { code: "A.6.2.5", title: "Despliegue del sistema de IA", parent: "A.6.2" },
        { code: "A.6.2.6", title: "Operación y monitoreo del sistema de IA", parent: "A.6.2", summary: "Métricas con umbrales, detección de deriva y gestión de cambios." },
        { code: "A.6.2.7", title: "Documentación técnica y retiro del sistema", parent: "A.6.2", summary: "Retiro con motivo, disposición de datos y modelos, y comunicación a los afectados." },
        { code: "A.7", title: "Datos para los sistemas de IA", parent: "A" },
        { code: "A.7.2", title: "Procedencia de los datos", parent: "A.7", summary: "Origen, licencia y cadena de transformaciones de cada dataset." },
        { code: "A.7.3", title: "Datos para el desarrollo y la mejora", parent: "A.7" },
        { code: "A.7.4", title: "Calidad de los datos", parent: "A.7", summary: "Completitud, exactitud, consistencia, actualidad y representatividad." },
        { code: "A.7.5", title: "Preparación de los datos", parent: "A.7" },
        { code: "A.7.6", title: "Privacidad y protección de datos personales", parent: "A.7", summary: "Base legal, categorías especiales, anonimización y retención." },
        { code: "A.8", title: "Información para las partes interesadas", parent: "A" },
        { code: "A.8.2", title: "Documentación del sistema para los usuarios", parent: "A.8" },
        { code: "A.8.3", title: "Comunicación de incidentes", parent: "A.8" },
        { code: "A.8.4", title: "Información para las personas afectadas", parent: "A.8", summary: "Aviso del uso de IA, limitaciones y canal de contacto humano." },
        { code: "A.9", title: "Uso responsable de los sistemas de IA", parent: "A" },
        { code: "A.9.2", title: "Supervisión humana y objetivos de uso responsable", parent: "A.9", summary: "Regla humana: ninguna salida de IA es registro oficial sin aprobación de una persona." },
        { code: "A.9.3", title: "Objetivos de equidad, transparencia y explicabilidad", parent: "A.9" },
        { code: "A.9.4", title: "Uso previsto del sistema de IA", parent: "A.9" },
        { code: "A.10", title: "Terceros y relaciones con clientes", parent: "A" },
        { code: "A.10.2", title: "Asignación de responsabilidades con terceros", parent: "A.10", summary: "Debida diligencia de proveedores de modelos, APIs y datasets." },
        { code: "A.10.3", title: "Proveedores", parent: "A.10" },
        { code: "A.10.4", title: "Gestión de incidentes de IA", parent: "A.10", summary: "Investigación con causa raíz, notificación y verificación de eficacia." },
      ],
      evidenceRules: [
        { requirementCode: "6.1.4", expectedType: "RECORD", frequency: "ANNUAL", note: "Evaluación de impacto por sistema de IA, aprobada por una persona." },
        { requirementCode: "6.1.2", expectedType: "RECORD", frequency: "ANNUAL", note: "Registro de riesgos de IA con nivel inherente, residual y aceptabilidad." },
        { requirementCode: "5.2", expectedType: "POLICY", frequency: "ANNUAL", note: "Política de IA con usos prohibidos y principios asumidos." },
        { requirementCode: "9.1", expectedType: "REPORT", frequency: "MONTHLY", note: "Monitoreo de sistemas en producción: desempeño, deriva y anulaciones humanas." },
        { requirementCode: "A.6.2.4", expectedType: "REPORT", note: "Informe de evaluación del modelo con métricas de sesgo y explicabilidad." },
        { requirementCode: "A.7.2", expectedType: "RECORD", note: "Inventario de datasets con fuentes, licencias y cadena de procedencia." },
        { requirementCode: "A.7.4", expectedType: "RECORD", frequency: "SEMIANNUAL", note: "Valoración de calidad de datos y revisión de sesgo del dataset." },
        { requirementCode: "A.8.4", expectedType: "RECORD", note: "Avisos de transparencia publicados a usuarios y personas afectadas." },
        { requirementCode: "A.9.2", expectedType: "RECORD", note: "Registro de salidas de IA con revisión humana: prompt, modelo, versión, revisor y decisión." },
        { requirementCode: "A.10.2", expectedType: "RECORD", frequency: "ANNUAL", note: "Evaluación de proveedores de IA (modelo, API o dataset)." },
        { requirementCode: "A.10.4", expectedType: "RECORD", note: "Investigación de incidentes de IA con causa raíz y notificación." },
      ],
      gapQuestions: [
        { requirementCode: "4.3", question: "¿Existe un inventario completo de los sistemas de IA en uso, con propietario, propósito y estado?", guidance: "Incluir la IA embebida en productos de terceros.", weight: 3 },
        { requirementCode: "6.1.4", question: "¿Se evalúa el impacto de cada sistema de IA sobre derechos, seguridad, privacidad y sesgo antes de su uso?", weight: 3 },
        { requirementCode: "6.1.2", question: "¿Los riesgos de IA se valoran y tratan con aceptación formal del riesgo residual?", weight: 3 },
        { requirementCode: "A.7.2", question: "¿Se documenta la procedencia de los datos y la cadena de transformaciones de cada dataset?", weight: 2 },
        { requirementCode: "A.7.4", question: "¿Se mide la calidad de los datos y se revisa el sesgo antes de entrenar o evaluar un modelo?", weight: 3 },
        { requirementCode: "A.6.2.4", question: "¿Los modelos se evalúan (desempeño, sesgo, robustez, explicabilidad) antes de pasar a producción?", weight: 3 },
        { requirementCode: "A.9.2", question: "¿Ninguna salida de IA se convierte en registro oficial sin una aprobación humana registrada?", guidance: "Comprobar el ciclo DRAFT → HUMAN_REVIEW → APPROVED/REJECTED y quién decidió.", weight: 3 },
        { requirementCode: "A.8.4", question: "¿Se informa a los usuarios y personas afectadas del uso de IA y de sus limitaciones?", weight: 2 },
        { requirementCode: "9.1", question: "¿Se monitorean los sistemas en producción con umbrales y detección de deriva?", weight: 2 },
        { requirementCode: "A.10.4", question: "¿Se investigan los incidentes de IA hasta la causa raíz y se decide la obligación de notificar?", weight: 3 },
        { requirementCode: "A.10.2", question: "¿Se evalúa a los proveedores de IA (documentación del modelo, evidencia de sesgo, uso de datos del cliente)?", weight: 2 },
        { requirementCode: "A.6.2.7", question: "¿El retiro de un sistema de IA exige motivo y plan de disposición de datos y modelos?", weight: 1 },
      ],
      auditChecklist: [
        { requirementCode: "4.3", question: "Verificar el inventario de sistemas de IA y su alcance declarado.", expectedEvidence: "Inventario con propietario, propósito, usuarios, criticidad y estado.", criterion: "Todo sistema en producción está inventariado y clasificado." },
        { requirementCode: "6.1.4", question: "Revisar las evaluaciones de impacto de los sistemas de riesgo alto.", expectedEvidence: "Evaluaciones con las siete dimensiones valoradas y aprobación humana.", criterion: "Sin evaluación aprobada no hay sistema en producción." },
        { requirementCode: "A.9.2", question: "Comprobar que ninguna salida de IA llegó a registro oficial sin revisión humana.", expectedEvidence: "Registro de salidas con prompt, modelo, versión, revisor, fecha y cambios humanos.", criterion: "Cero salidas promovidas en estado distinto de APPROVED." },
        { requirementCode: "A.6.2.4", question: "Revisar la evaluación de los modelos en producción.", expectedEvidence: "Informes con métricas de desempeño, equidad y explicabilidad.", criterion: "Modelo en producción con evaluación superada y dataset con sesgo revisado." },
        { requirementCode: "A.7.2", question: "Trazar la procedencia de un dataset de extremo a extremo.", expectedEvidence: "Fuentes declaradas y pasos de linaje sin huecos.", criterion: "Cadena de procedencia completa y auditable." },
        { requirementCode: "9.1", question: "Verificar el monitoreo continuo y la respuesta a incumplimientos de umbral.", expectedEvidence: "Métricas por periodo con umbral, deriva y acciones derivadas.", criterion: "Sistemas en producción monitoreados en el periodo auditado." },
        { requirementCode: "A.10.4", question: "Revisar los incidentes de IA y su cierre.", expectedEvidence: "Investigación con causa raíz, notificación y verificación de eficacia.", criterion: "Flujo completo hasta la verificación de eficacia." },
      ],
      templates: [
        { requirementCode: "5.2", templateType: "POLICY", name: "Política de Inteligencia Artificial (plantilla)", content: "" },
        { requirementCode: "6.1.4", templateType: "RECORD", name: "Evaluación de Impacto de IA (plantilla)", content: "" },
        { requirementCode: "A.9.2", templateType: "PROCEDURE", name: "Procedimiento de Revisión Humana de Salidas de IA (plantilla)", content: "" },
        { requirementCode: "A.7.2", templateType: "RECORD", name: "Ficha de Dataset y Procedencia (plantilla)", content: "" },
        { requirementCode: "A.6.2.4", templateType: "RECORD", name: "Informe de Evaluación de Modelo (plantilla)", content: "" },
        { requirementCode: "A.10.4", templateType: "PROCEDURE", name: "Procedimiento de Gestión de Incidentes de IA (plantilla)", content: "" },
      ],
    },
  ],
  /**
   * Estructura común del Anexo SL con ISO 9001 y solapes concretos con ISO 27001
   * (seguridad de la información) para no duplicar controles ni evidencias.
   */
  mappings: [
    { sourceFamily: "ISO_42001", sourceCode: "4.1", targetFamily: "ISO_9001", targetCode: "4.1", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_42001", sourceCode: "4.2", targetFamily: "ISO_9001", targetCode: "4.2", relationType: "PARTIAL", equivalencePercent: 70, notes: "El SGIA añade a las personas afectadas por la IA como parte interesada." },
    { sourceFamily: "ISO_42001", sourceCode: "5.2", targetFamily: "ISO_9001", targetCode: "5.2", relationType: "PARTIAL", equivalencePercent: 70, notes: "Política de IA ⇄ política de calidad (misma estructura, alcance distinto)." },
    { sourceFamily: "ISO_42001", sourceCode: "7.5", targetFamily: "ISO_9001", targetCode: "7.5", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_42001", sourceCode: "9.2", targetFamily: "ISO_9001", targetCode: "9.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_42001", sourceCode: "9.3", targetFamily: "ISO_9001", targetCode: "9.3", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_42001", sourceCode: "10.2", targetFamily: "ISO_9001", targetCode: "10.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_42001", sourceCode: "6.3", targetFamily: "ISO_9001", targetCode: "6.3", relationType: "PARTIAL", equivalencePercent: 70, notes: "Cambios del sistema de IA ⇄ planificación de cambios." },
    { sourceFamily: "ISO_42001", sourceCode: "6.1.2", targetFamily: "ISO_27001", targetCode: "6.1.2", relationType: "PARTIAL", equivalencePercent: 60, notes: "Misma mecánica de valoración; el riesgo de IA añade sesgo, explicabilidad y daño a personas." },
    { sourceFamily: "ISO_42001", sourceCode: "6.1.3", targetFamily: "ISO_27001", targetCode: "6.1.3", relationType: "PARTIAL", equivalencePercent: 60, notes: "Tratamiento del riesgo de IA ⇄ tratamiento del riesgo de seguridad de la información." },
    { sourceFamily: "ISO_42001", sourceCode: "A.7.6", targetFamily: "ISO_27001", targetCode: "A.5", relationType: "RELATED", equivalencePercent: 60, notes: "Privacidad de los datos de entrenamiento ⇄ controles organizacionales de privacidad (A.5.34)." },
    { sourceFamily: "ISO_42001", sourceCode: "A.10.2", targetFamily: "ISO_27001", targetCode: "A.5", relationType: "RELATED", equivalencePercent: 60, notes: "Proveedores de IA ⇄ controles de relaciones con proveedores (A.5.19–A.5.23)." },
    { sourceFamily: "ISO_42001", sourceCode: "A.10.4", targetFamily: "ISO_27001", targetCode: "A.5", relationType: "RELATED", equivalencePercent: 60, notes: "Incidentes de IA ⇄ gestión de incidentes de seguridad de la información (A.5.24–A.5.28)." },
  ],
};
