import type { StandardPackInput } from "./pack-schema";

/**
 * ISO 22301:2019 — Continuidad del negocio (BCMS).
 * Títulos y resúmenes propios. No texto normativo protegido.
 * Requiere módulo `continuity` (BIA, planes, crisis, ejercicios).
 */
export const iso22301Pack: StandardPackInput = {
  code: "PACK_ISO_22301",
  name: "ISO 22301 — Continuidad del negocio",
  version: "2019.1",
  description:
    "Paquete normativo ISO 22301:2019 (BCMS): BIA, estrategias, planes, crisis y ejercicios. No promete continuidad automática sin operación humana.",
  lifecycleStatus: "PILOT",
  requiredModules: [
    "gap", "documents", "audits", "nonconformities", "actions", "risks", "indicators", "management-review", "continuity",
  ],
  featureFlags: { businessContinuity: true, bia: true },
  editions: [
    {
      familyCode: "ISO_22301",
      familyName: "ISO 22301",
      category: "Continuidad del negocio",
      familyDescription: "Sistema de Gestión de Continuidad del Negocio",
      editionCode: "2019",
      name: "ISO 22301",
      version: "2019",
      year: 2019,
      description: "Seguridad y resiliencia — Sistemas de gestión de la continuidad del negocio",
      catalogVersion: "2019.1",
      status: "ACTIVE",
      requirements: [
        { code: "4", title: "Contexto de la organización" },
        { code: "4.1", title: "Comprensión de la organización y de su contexto", parent: "4" },
        { code: "4.2", title: "Comprensión de las necesidades y expectativas de las partes interesadas", parent: "4" },
        { code: "4.3", title: "Determinación del alcance del SGCN", parent: "4" },
        { code: "4.4", title: "Sistema de gestión de la continuidad del negocio", parent: "4" },
        { code: "5", title: "Liderazgo" },
        { code: "5.1", title: "Liderazgo y compromiso", parent: "5" },
        { code: "5.2", title: "Política", parent: "5" },
        { code: "5.3", title: "Roles, responsabilidades y autoridades", parent: "5" },
        { code: "6", title: "Planificación" },
        { code: "6.1", title: "Acciones para abordar riesgos y oportunidades", parent: "6" },
        { code: "6.2", title: "Objetivos de continuidad y planificación para lograrlos", parent: "6" },
        { code: "6.3", title: "Planificación de los cambios", parent: "6" },
        { code: "7", title: "Apoyo" },
        { code: "7.1", title: "Recursos", parent: "7" },
        { code: "7.2", title: "Competencia", parent: "7" },
        { code: "7.3", title: "Toma de conciencia", parent: "7" },
        { code: "7.4", title: "Comunicación", parent: "7" },
        { code: "7.5", title: "Información documentada", parent: "7" },
        { code: "8", title: "Operación" },
        { code: "8.1", title: "Planificación y control operacional", parent: "8" },
        { code: "8.2", title: "Análisis de impacto al negocio (BIA) y evaluación de riesgos", parent: "8", summary: "MTPD, RTO, RPO y dependencias." },
        { code: "8.3", title: "Estrategias de continuidad del negocio", parent: "8" },
        { code: "8.4", title: "Planes y procedimientos de continuidad", parent: "8" },
        { code: "8.5", title: "Ejercicio y prueba", parent: "8" },
        { code: "8.6", title: "Evaluación de la documentación y de las capacidades de continuidad", parent: "8" },
        { code: "9", title: "Evaluación del desempeño" },
        { code: "9.1", title: "Seguimiento, medición, análisis y evaluación", parent: "9" },
        { code: "9.2", title: "Auditoría interna", parent: "9" },
        { code: "9.3", title: "Revisión por la dirección", parent: "9" },
        { code: "10", title: "Mejora" },
        { code: "10.1", title: "No conformidad y acciones correctivas", parent: "10" },
        { code: "10.2", title: "Mejora continua", parent: "10" },
      ],
      evidenceRules: [
        { requirementCode: "5.2", expectedType: "POLICY", note: "Política de continuidad aprobada." },
        { requirementCode: "8.2", expectedType: "RECORD", frequency: "ANNUAL", note: "BIA con MTPD/RTO/RPO." },
        { requirementCode: "8.3", expectedType: "RECORD", note: "Estrategias de recuperación documentadas." },
        { requirementCode: "8.4", expectedType: "PROCEDURE", note: "Planes BCP versionados y aprobados." },
        { requirementCode: "8.5", expectedType: "RECORD", frequency: "ANNUAL", note: "Resultados de ejercicios/pruebas." },
        { requirementCode: "9.2", expectedType: "REPORT", frequency: "ANNUAL", note: "Auditoría interna BCMS." },
      ],
      gapQuestions: [
        { requirementCode: "4.3", question: "¿El alcance del SGCN incluye productos/servicios prioritarios y exclusiones justificadas?", weight: 2 },
        { requirementCode: "8.2", question: "¿Existe BIA actualizado con MTPD ≥ RTO por actividad crítica?", weight: 3 },
        { requirementCode: "8.3", question: "¿Hay estrategias de continuidad para dependencias críticas (personas, TI, proveedores)?", weight: 3 },
        { requirementCode: "8.4", question: "¿Los planes BCP están versionados, aprobados y accesibles en crisis?", weight: 3 },
        { requirementCode: "8.5", question: "¿Se ejercitan los planes al menos anualmente con lecciones aprendidas?", weight: 3 },
        { requirementCode: "9.3", question: "¿La dirección revisa el desempeño del SGCN con métricas de preparación?", weight: 2 },
      ],
      auditChecklist: [
        { requirementCode: "8.2", question: "Revisar una BIA con actividades críticas y RTO≤MTPD.", expectedEvidence: "BusinessImpactAnalysis + CriticalActivity", criterion: "Sin RTO > MTPD." },
        { requirementCode: "8.4", question: "Verificar versión aprobada de un BCP.", expectedEvidence: "BusinessContinuityPlan APPROVED + ContinuityPlanVersion", criterion: "Atribución de aprobador." },
        { requirementCode: "8.5", question: "Revisar un ejercicio COMPLETED con hallazgos.", expectedEvidence: "ContinuityTest + escenarios", criterion: "Acciones de mejora enlazadas." },
        { requirementCode: "8.3", question: "Comprobar estrategia para una dependencia de proveedor crítico.", expectedEvidence: "ContinuityStrategy + BusinessDependency", criterion: "Recurso alterno definido." },
      ],
      templates: [
        { requirementCode: "5.2", templateType: "POLICY", name: "Política de continuidad del negocio (plantilla)", content: "" },
        { requirementCode: "8.2", templateType: "RECORD", name: "Registro BIA — actividades críticas (plantilla)", content: "" },
        { requirementCode: "8.4", templateType: "PROCEDURE", name: "Plan de continuidad del negocio — BCP (plantilla)", content: "" },
        { requirementCode: "8.5", templateType: "RECORD", name: "Acta de ejercicio de continuidad (plantilla)", content: "" },
      ],
    },
  ],
  mappings: [
    { sourceFamily: "ISO_22301", sourceCode: "4.1", targetFamily: "ISO_9001", targetCode: "4.1", relationType: "EQUIVALENT", equivalencePercent: 90 },
    { sourceFamily: "ISO_22301", sourceCode: "5.2", targetFamily: "ISO_9001", targetCode: "5.2", relationType: "PARTIAL", equivalencePercent: 70 },
    { sourceFamily: "ISO_22301", sourceCode: "6.1", targetFamily: "ISO_9001", targetCode: "6.1", relationType: "RELATED", equivalencePercent: 60 },
    { sourceFamily: "ISO_22301", sourceCode: "8.2", targetFamily: "ISO_27001", targetCode: "8.2", relationType: "RELATED", equivalencePercent: 40, notes: "BIA de negocio ⇄ evaluación de riesgos de seguridad; ámbitos distintos." },
    { sourceFamily: "ISO_22301", sourceCode: "9.2", targetFamily: "ISO_9001", targetCode: "9.2", relationType: "EQUIVALENT", equivalencePercent: 95 },
    { sourceFamily: "ISO_22301", sourceCode: "10.1", targetFamily: "ISO_9001", targetCode: "10.2", relationType: "EQUIVALENT", equivalencePercent: 90 },
  ],
};
