import type { StandardPackInput } from "./pack-schema";

/**
 * ISO 50001:2018 — Sistema de Gestión de la Energía (SGEn).
 * Códigos de cláusula y títulos propios de NormaFlow — nunca el texto protegido.
 */
export const iso50001Pack: StandardPackInput = {
  code: "PACK_ISO_50001",
  name: "ISO 50001 — Energía",
  version: "2018.1",
  lifecycleStatus: "DEVELOPMENT",
  description: "Paquete normativo ISO 50001:2018 (Sistema de Gestión de la Energía).",
  requiredModules: [
    "gap", "documents", "audits", "nonconformities", "actions", "indicators", "management-review", "energy",
  ],
  featureFlags: { energyManagement: true, enpiFormulas: true },
  editions: [
    {
      familyCode: "ISO_50001",
      familyName: "ISO 50001",
      category: "Energía",
      familyDescription: "Sistema de Gestión de la Energía",
      editionCode: "2018",
      name: "ISO 50001",
      version: "2018",
      year: 2018,
      description: "Sistema de Gestión de la Energía (SGEn)",
      catalogVersion: "2018.1",
      status: "ACTIVE",
      requirements: [
        { code: "4", title: "Contexto de la organización" },
        { code: "4.1", title: "Comprensión de la organización y de su contexto", parent: "4" },
        { code: "4.2", title: "Comprensión de las necesidades y expectativas de las partes interesadas", parent: "4" },
        { code: "4.3", title: "Determinación del alcance del sistema de gestión de la energía", parent: "4" },
        { code: "4.4", title: "Sistema de gestión de la energía", parent: "4" },
        { code: "5", title: "Liderazgo" },
        { code: "5.1", title: "Liderazgo y compromiso", parent: "5" },
        { code: "5.2", title: "Política energética", parent: "5" },
        { code: "5.3", title: "Roles, responsabilidades y autoridades en la organización", parent: "5" },
        { code: "6", title: "Planificación" },
        { code: "6.1", title: "Acciones para abordar riesgos y oportunidades", parent: "6" },
        { code: "6.2", title: "Objetivos, metas energéticas y planificación para lograrlos", parent: "6" },
        { code: "6.3", title: "Revisión energética", parent: "6", summary: "Análisis de usos y consumos, determinación de SEU, variables relevantes y oportunidades." },
        { code: "6.4", title: "Indicadores de desempeño energético", parent: "6", summary: "EnPI con fórmulas configurables y versionadas." },
        { code: "6.5", title: "Línea de base energética", parent: "6", summary: "Línea base con método de normalización versionado." },
        { code: "6.6", title: "Planificación de la recolección de datos energéticos", parent: "6" },
        { code: "7", title: "Apoyo" },
        { code: "7.1", title: "Recursos", parent: "7" },
        { code: "7.2", title: "Competencia", parent: "7" },
        { code: "7.3", title: "Toma de conciencia", parent: "7" },
        { code: "7.4", title: "Comunicación", parent: "7" },
        { code: "7.5", title: "Información documentada", parent: "7" },
        { code: "8", title: "Operación" },
        { code: "8.1", title: "Planificación y control operacional", parent: "8" },
        { code: "8.2", title: "Diseño", parent: "8", summary: "Consideración de desempeño energético en diseño de instalaciones, equipos y procesos." },
        { code: "8.3", title: "Adquisición", parent: "8", summary: "Evaluación energética en la compra de energía, productos y servicios." },
        { code: "9", title: "Evaluación del desempeño" },
        { code: "9.1", title: "Seguimiento, medición, análisis y evaluación del desempeño energético", parent: "9", summary: "Medidores, lecturas, EnPI, comparación con línea base y desviaciones." },
        { code: "9.1.1", title: "Generalidades", parent: "9.1" },
        { code: "9.1.2", title: "Evaluación del cumplimiento de los requisitos legales y otros requisitos", parent: "9.1" },
        { code: "9.2", title: "Auditoría interna", parent: "9" },
        { code: "9.3", title: "Revisión por la dirección", parent: "9" },
        { code: "10", title: "Mejora" },
        { code: "10.1", title: "No conformidad y acción correctiva", parent: "10" },
        { code: "10.2", title: "Mejora continua", parent: "10", summary: "Oportunidades, planes de acción y verificación de ahorros (absoluto y normalizado)." },
      ],
      evidenceRules: [
        { requirementCode: "6.3", expectedType: "RECORD", frequency: "ANNUAL", note: "Revisión energética con SEU, variables y oportunidades." },
        { requirementCode: "6.4", expectedType: "RECORD", frequency: "ANNUAL", note: "EnPI con fórmula y versión documentadas." },
        { requirementCode: "6.5", expectedType: "RECORD", frequency: "ANNUAL", note: "Línea base energética con método de normalización." },
        { requirementCode: "8.2", expectedType: "RECORD", note: "Revisiones de diseño con consideraciones energéticas." },
        { requirementCode: "8.3", expectedType: "RECORD", frequency: "ANNUAL", note: "Evaluaciones de compra de energía / equipos energéticos." },
        { requirementCode: "9.1", expectedType: "REPORT", frequency: "MONTHLY", note: "Consumos, EnPI y desviaciones respecto a la línea base." },
        { requirementCode: "10.2", expectedType: "RECORD", note: "Planes de acción y verificación de ahorros." },
      ],
      gapQuestions: [
        { requirementCode: "6.3", question: "¿Existe una revisión energética que identifique usos significativos (SEU)?", weight: 3 },
        { requirementCode: "6.4", question: "¿Los EnPI tienen fórmula documentada y versionada?", guidance: "Comprobar supersesión de versiones al cambiar la fórmula.", weight: 3 },
        { requirementCode: "6.5", question: "¿Hay línea base energética con normalización cuando las variables relevantes cambian?", weight: 3 },
        { requirementCode: "9.1", question: "¿Se registran lecturas de medidores y se calculan coste y emisiones asociadas?", weight: 2 },
        { requirementCode: "8.2", question: "¿El diseño de nuevas instalaciones considera el desempeño energético?", weight: 2 },
        { requirementCode: "8.3", question: "¿Las compras de energía evalúan criterios energéticos además del precio?", weight: 2 },
        { requirementCode: "10.2", question: "¿Los ahorros de los planes de acción se verifican (absoluto y/o normalizado)?", weight: 3 },
      ],
      auditChecklist: [
        { requirementCode: "6.3", question: "Revisar la última revisión energética y el registro de SEU.", expectedEvidence: "Revisión aprobada + SEU con participación/potencial.", criterion: "SEU justificados y vinculados a la revisión." },
        { requirementCode: "6.4", question: "Verificar EnPI activos y su versión de fórmula.", expectedEvidence: "EnPI con formulaKind, formulaVersion y config.", criterion: "No hay EnPI activo sin fórmula versionada." },
        { requirementCode: "6.5", question: "Comprobar línea base y normalización.", expectedEvidence: "Baseline con método NONE/RATIO/LINEAR y consumo normalizado.", criterion: "Versiones anteriores quedan SUPERSEDED." },
        { requirementCode: "9.1", question: "Muestrear lecturas de medidores del periodo.", expectedEvidence: "Lecturas con valor, coste y emisiones cuando la fuente lo permite.", criterion: "Consumo del periodo reconstruible desde lecturas." },
        { requirementCode: "10.2", question: "Revisar verificación de ahorro de un plan cerrado.", expectedEvidence: "Verificación VERIFIED con ahorro absoluto/normalizado.", criterion: "Cierre solo con verificador atribuido." },
      ],
      templates: [
        { requirementCode: "5.2", templateType: "POLICY", name: "Política Energética (plantilla)", content: "" },
        { requirementCode: "6.3", templateType: "RECORD", name: "Revisión Energética (plantilla)", content: "" },
        { requirementCode: "6.4", templateType: "RECORD", name: "Ficha de EnPI (plantilla)", content: "" },
        { requirementCode: "10.2", templateType: "RECORD", name: "Verificación de Ahorro Energético (plantilla)", content: "" },
      ],
    },
  ],
  mappings: [
    { sourceFamily: "ISO_50001", sourceCode: "4.1", targetFamily: "ISO_9001", targetCode: "4.1", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_50001", sourceCode: "5.2", targetFamily: "ISO_9001", targetCode: "5.2", relationType: "PARTIAL", equivalencePercent: 70, notes: "Política energética ⇄ política de calidad." },
    { sourceFamily: "ISO_50001", sourceCode: "7.5", targetFamily: "ISO_9001", targetCode: "7.5", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_50001", sourceCode: "9.2", targetFamily: "ISO_9001", targetCode: "9.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_50001", sourceCode: "9.3", targetFamily: "ISO_9001", targetCode: "9.3", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_50001", sourceCode: "10.1", targetFamily: "ISO_9001", targetCode: "10.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_50001", sourceCode: "6.3", targetFamily: "ISO_14001", targetCode: "6.1.2", relationType: "RELATED", equivalencePercent: 40, notes: "Revisión energética ⇄ aspectos ambientales (perspectiva de uso de energía)." },
    { sourceFamily: "ISO_50001", sourceCode: "9.1", targetFamily: "ISO_14001", targetCode: "9.1.1", relationType: "RELATED", equivalencePercent: 50, notes: "Seguimiento energético ⇄ seguimiento ambiental; no se duplica EnvironmentalMetric.energy." },
    { sourceFamily: "ISO_50001", sourceCode: "8.3", targetFamily: "ISO_9001", targetCode: "8.4", relationType: "RELATED", equivalencePercent: 50, notes: "Adquisición energética ⇄ control de procesos, productos y servicios suministrados externamente." },
  ],
};
