import type { StandardPackInput } from "./pack-schema";

/**
 * ISO 37301:2021 — Sistema de Gestión de Compliance (SGC).
 *
 * Solo códigos de cláusula, estructura y títulos/resúmenes propios de NormaFlow
 * — nunca el texto protegido de la norma. Los ids resuelven a la forma estable
 * `req-iso-37301-<code>` vía `requirementIdFor`.
 *
 * El canal de denuncias aparece con su propio detalle (§8.3) porque es donde la
 * norma exige lo que el módulo automatiza: recepción con modo de identificación,
 * confidencialidad, protección frente a represalias, investigación independiente
 * y cierre con retención.
 */
export const iso37301Pack: StandardPackInput = {
  code: "PACK_ISO_37301",
  name: "ISO 37301 — Compliance",
  version: "2021.1",
  lifecycleStatus: "PILOT",
  description: "Paquete normativo ISO 37301:2021 (Sistema de Gestión de Compliance).",
  requiredModules: [
    "gap", "documents", "audits", "nonconformities", "actions", "indicators", "management-review", "training", "suppliers", "risks",
    "compliance", "speakup",
  ],
  featureFlags: { complianceManagement: true, speakUpChannel: true, obligationRegister: true },
  editions: [
    {
      familyCode: "ISO_37301",
      familyName: "ISO 37301",
      category: "Compliance",
      familyDescription: "Sistema de Gestión de Compliance",
      editionCode: "2021",
      name: "ISO 37301",
      version: "2021",
      year: 2021,
      description: "Sistema de Gestión de Compliance (SGC)",
      catalogVersion: "2021.1",
      status: "ACTIVE",
      requirements: [
        { code: "4", title: "Contexto de la organización" },
        { code: "4.1", title: "Comprensión de la organización y de su contexto", parent: "4" },
        { code: "4.2", title: "Comprensión de las necesidades y expectativas de las partes interesadas", parent: "4", summary: "Incluye autoridades, clientes, personal y terceros con expectativas de cumplimiento." },
        { code: "4.3", title: "Determinación del alcance del sistema de gestión de compliance", parent: "4" },
        { code: "4.4", title: "Sistema de gestión de compliance", parent: "4" },
        { code: "4.5", title: "Principios de buena gobernanza", parent: "4" },
        { code: "4.6", title: "Obligaciones de compliance", parent: "4", summary: "Registro de obligaciones legales, regulatorias, contractuales y voluntarias, con jurisdicción, fuente y responsable." },
        { code: "5", title: "Liderazgo" },
        { code: "5.1", title: "Liderazgo y compromiso", parent: "5" },
        { code: "5.1.1", title: "Órgano de gobierno y alta dirección", parent: "5.1", summary: "Rendición de cuentas del órgano de gobierno sobre el compliance." },
        { code: "5.1.2", title: "Cultura de compliance", parent: "5.1", summary: "Informes periódicos al órgano de gobierno y tono desde arriba." },
        { code: "5.1.3", title: "Gobernanza de compliance", parent: "5.1" },
        { code: "5.2", title: "Política de compliance", parent: "5" },
        { code: "5.3", title: "Roles, responsabilidades y autoridades", parent: "5" },
        { code: "5.3.1", title: "Función de compliance", parent: "5.3", summary: "Independencia, autoridad y acceso directo al órgano de gobierno." },
        { code: "5.3.2", title: "Responsabilidad de la dirección", parent: "5.3" },
        { code: "5.3.3", title: "Responsabilidad del personal", parent: "5.3" },
        { code: "6", title: "Planificación" },
        { code: "6.1", title: "Acciones para abordar riesgos y oportunidades", parent: "6", summary: "Identificación, análisis y evaluación de riesgos de compliance: probabilidad de incumplir por consecuencia." },
        { code: "6.2", title: "Objetivos de compliance y planificación para lograrlos", parent: "6" },
        { code: "6.3", title: "Planificación de los cambios", parent: "6", summary: "Cambios regulatorios y organizativos con análisis de impacto previo." },
        { code: "7", title: "Apoyo" },
        { code: "7.1", title: "Recursos", parent: "7" },
        { code: "7.2", title: "Competencia", parent: "7" },
        { code: "7.2.1", title: "Competencia y formación", parent: "7.2", summary: "Formación en compliance con audiencia, obligatoriedad, cobertura y eficacia." },
        { code: "7.2.2", title: "Proceso de empleo", parent: "7.2", summary: "Debida diligencia de personas, conflictos de interés y declaraciones." },
        { code: "7.3", title: "Toma de conciencia", parent: "7" },
        { code: "7.4", title: "Comunicación", parent: "7" },
        { code: "7.5", title: "Información documentada", parent: "7" },
        { code: "8", title: "Operación" },
        { code: "8.1", title: "Planificación y control operacional", parent: "8", summary: "Controles de compliance, calendario de obligaciones y vigilancia regulatoria." },
        { code: "8.2", title: "Establecimiento de controles y procedimientos", parent: "8", summary: "Controles preventivos, detectivos y correctivos, con prueba periódica de diseño y eficacia." },
        { code: "8.3", title: "Planteamiento de preocupaciones", parent: "8", summary: "Canal de denuncias: reporte identificado, confidencial o anónimo, sin represalias." },
        { code: "8.3.1", title: "Acceso al canal y modos de reporte", parent: "8.3", summary: "El anonimato existe solo si la organización lo habilita, y entonces la identidad no se almacena." },
        { code: "8.3.2", title: "Confidencialidad y protección frente a represalias", parent: "8.3", summary: "Acceso restringido por necesidad de conocer y medidas de protección del informante." },
        { code: "8.4", title: "Procesos de investigación", parent: "8", summary: "Investigación independiente: quien está señalado no investiga, y el conflicto obliga a recusación." },
        { code: "9", title: "Evaluación del desempeño" },
        { code: "9.1", title: "Seguimiento, medición, análisis y evaluación", parent: "9" },
        { code: "9.1.1", title: "Generalidades", parent: "9.1" },
        { code: "9.1.2", title: "Fuentes de retroalimentación", parent: "9.1" },
        { code: "9.1.3", title: "Desarrollo de indicadores", parent: "9.1" },
        { code: "9.1.4", title: "Evaluación del cumplimiento", parent: "9.1", summary: "Evaluación periódica de cada obligación aplicable, con resultado revisado por una persona." },
        { code: "9.1.5", title: "Informes de compliance", parent: "9.1" },
        { code: "9.1.6", title: "Mantenimiento de registros", parent: "9.1" },
        { code: "9.2", title: "Auditoría interna", parent: "9" },
        { code: "9.3", title: "Revisión por la dirección", parent: "9", summary: "Revisión con obligaciones, riesgos, evaluaciones, canal (agregado), incumplimientos y remediación." },
        { code: "10", title: "Mejora" },
        { code: "10.1", title: "Mejora continua", parent: "10" },
        { code: "10.2", title: "No conformidad y acción correctiva", parent: "10", summary: "Incumplimientos con causa raíz, notificación a la autoridad cuando proceda y remediación verificada." },

        // Anexo A — guía de implementación.
        { code: "A", title: "Anexo A — Guía de implementación" },
        { code: "A.4", title: "Contexto y obligaciones", parent: "A" },
        { code: "A.4.6", title: "Identificación y evaluación de obligaciones", parent: "A.4", summary: "Aplicabilidad por jurisdicción con motivo documentado." },
        { code: "A.5", title: "Liderazgo y cultura", parent: "A" },
        { code: "A.5.1", title: "Informes al órgano de gobierno", parent: "A.5" },
        { code: "A.6", title: "Riesgos de compliance", parent: "A" },
        { code: "A.6.1", title: "Valoración y tratamiento del riesgo de compliance", parent: "A.6" },
        { code: "A.8", title: "Operación", parent: "A" },
        { code: "A.8.2", title: "Diseño y prueba de controles", parent: "A.8" },
        { code: "A.8.3", title: "Canal de denuncias", parent: "A.8", summary: "Plazos de acuse y respuesta, evidencia protegida y retención del expediente." },
        { code: "A.8.4", title: "Investigación y conflicto de interés", parent: "A.8" },
        { code: "A.9", title: "Desempeño", parent: "A" },
        { code: "A.9.1", title: "Indicadores y evaluación del cumplimiento", parent: "A.9" },
        { code: "A.10", title: "Mejora", parent: "A" },
        { code: "A.10.1", title: "Remediación y verificación de eficacia", parent: "A.10" },
      ],
      evidenceRules: [
        { requirementCode: "4.6", expectedType: "RECORD", frequency: "SEMIANNUAL", note: "Registro de obligaciones con fuente, jurisdicción, responsable y criticidad." },
        { requirementCode: "5.2", expectedType: "POLICY", frequency: "ANNUAL", note: "Política de compliance aprobada por el órgano de gobierno." },
        { requirementCode: "5.1.2", expectedType: "REPORT", frequency: "SEMIANNUAL", note: "Informe de compliance al órgano de gobierno, con acuse registrado." },
        { requirementCode: "6.1", expectedType: "RECORD", frequency: "ANNUAL", note: "Valoración de riesgos de compliance con nivel inherente, residual y aceptabilidad." },
        { requirementCode: "7.2.1", expectedType: "RECORD", frequency: "ANNUAL", note: "Formación en compliance con audiencia, cobertura y evaluación de eficacia." },
        { requirementCode: "7.2.2", expectedType: "RECORD", frequency: "ANNUAL", note: "Declaraciones de conflicto de interés del personal expuesto." },
        { requirementCode: "8.1", expectedType: "RECORD", frequency: "MONTHLY", note: "Calendario de obligaciones con vencimientos, responsable y evidencia de presentación." },
        { requirementCode: "8.2", expectedType: "RECORD", frequency: "QUARTERLY", note: "Prueba de controles: diseño adecuado y operación eficaz." },
        { requirementCode: "8.3", expectedType: "PROCEDURE", frequency: "ANNUAL", note: "Procedimiento del canal de denuncias con modos de reporte y protección del informante." },
        { requirementCode: "8.4", expectedType: "RECORD", retentionMonths: 60, note: "Expediente de investigación con hallazgos, conclusión y control de independencia." },
        { requirementCode: "9.1.4", expectedType: "RECORD", frequency: "SEMIANNUAL", note: "Evaluación del cumplimiento por obligación, aprobada por una persona." },
        { requirementCode: "10.2", expectedType: "RECORD", note: "Incumplimientos con causa raíz, notificación a la autoridad y remediación verificada." },
      ],
      gapQuestions: [
        { requirementCode: "4.6", question: "¿Existe un registro de obligaciones de compliance con su fuente, jurisdicción y responsable?", guidance: "Debe incluir obligaciones legales, regulatorias, contractuales y compromisos voluntarios.", weight: 3 },
        { requirementCode: "A.4.6", question: "¿La aplicabilidad de cada obligación está decidida y motivada por jurisdicción?", guidance: "Una obligación \"no aplicable\" sin motivo documentado es una obligación sin evaluar.", weight: 3 },
        { requirementCode: "6.1", question: "¿Los riesgos de compliance se valoran y se tratan, con aceptación formal del riesgo residual?", weight: 3 },
        { requirementCode: "8.2", question: "¿Los controles de compliance se prueban periódicamente en diseño y en operación?", weight: 2 },
        { requirementCode: "8.1", question: "¿Existe un calendario de obligaciones con alertas antes del vencimiento?", weight: 2 },
        { requirementCode: "8.3", question: "¿El canal de denuncias admite reporte identificado, confidencial y anónimo cuando la organización lo permite?", guidance: "Comprobar que en modo anónimo no se almacena ningún dato del informante.", weight: 3 },
        { requirementCode: "8.3.2", question: "¿El acceso a un caso del canal está restringido a personas autorizadas caso por caso?", guidance: "Tener permisos del módulo no debe bastar para abrir un expediente.", weight: 3 },
        { requirementCode: "8.4", question: "¿Se comprueba la independencia de quien investiga y se recusa ante conflicto de interés?", weight: 3 },
        { requirementCode: "9.1.4", question: "¿Se evalúa periódicamente el cumplimiento de cada obligación aplicable?", weight: 3 },
        { requirementCode: "9.3", question: "¿El órgano de gobierno recibe informes de compliance y deja constancia de sus decisiones?", weight: 2 },
        { requirementCode: "10.2", question: "¿Los incumplimientos se remedian y su eficacia se verifica por alguien distinto del ejecutor?", weight: 3 },
        { requirementCode: "7.2.2", question: "¿El personal expuesto declara sus conflictos de interés y alguien independiente los revisa?", weight: 2 },
        { requirementCode: "A.8.3", question: "¿Los casos del canal tienen plazo de retención y se purgan al vencer?", guidance: "Ni antes, porque son prueba, ni indefinidamente, porque son datos personales.", weight: 1 },
      ],
      auditChecklist: [
        { requirementCode: "4.6", question: "Revisar el registro de obligaciones y su trazabilidad a la fuente.", expectedEvidence: "Obligaciones con fuente regulatoria, artículo, jurisdicción y responsable.", criterion: "Toda obligación aplicable tiene fuente identificada y responsable asignado." },
        { requirementCode: "A.4.6", question: "Verificar la evaluación de aplicabilidad por jurisdicción.", expectedEvidence: "Decisiones con motivo, criterios, evaluador y fecha.", criterion: "Ninguna decisión de aplicabilidad sin motivo documentado." },
        { requirementCode: "9.1.4", question: "Comprobar la evaluación del cumplimiento del periodo.", expectedEvidence: "Evaluaciones con resultado, hallazgos y revisión aprobada.", criterion: "Solo una evaluación aprobada por una persona mueve el estado de la obligación." },
        { requirementCode: "8.3", question: "Verificar el funcionamiento del canal de denuncias.", expectedEvidence: "Casos con modo de identificación, acuse en plazo y respuesta al informante.", criterion: "Acuse dentro del plazo configurado y ningún dato de informante en casos anónimos." },
        { requirementCode: "8.3.2", question: "Revisar las autorizaciones de acceso a los casos.", expectedEvidence: "Lista de acceso por caso, con motivo de la necesidad de conocer y revocaciones motivadas.", criterion: "Acceso limitado a personas autorizadas; la persona señalada nunca tiene acceso." },
        { requirementCode: "8.4", question: "Revisar la independencia de las investigaciones.", expectedEvidence: "Comprobación de conflicto, recusaciones y reasignaciones.", criterion: "Ninguna investigación dirigida por la persona señalada o con conflicto declarado." },
        { requirementCode: "10.2", question: "Revisar incumplimientos, notificación a la autoridad y remediación.", expectedEvidence: "Causa raíz, notificación con fecha y verificación de eficacia por un tercero interno.", criterion: "Cierre solo con remediación verificada y notificación cuando era obligatoria." },
        { requirementCode: "5.1.2", question: "Comprobar los informes al órgano de gobierno.", expectedEvidence: "Informes del periodo con acuse registrado y decisiones tomadas.", criterion: "El canal aparece solo agregado, sin identidades." },
      ],
      templates: [
        { requirementCode: "5.2", templateType: "POLICY", name: "Política de Compliance (plantilla)", content: "" },
        { requirementCode: "4.6", templateType: "RECORD", name: "Registro de Obligaciones de Compliance (plantilla)", content: "" },
        { requirementCode: "8.3", templateType: "PROCEDURE", name: "Procedimiento del Canal de Denuncias (plantilla)", content: "" },
        { requirementCode: "8.4", templateType: "PROCEDURE", name: "Procedimiento de Investigación Interna (plantilla)", content: "" },
        { requirementCode: "7.2.2", templateType: "RECORD", name: "Declaración de Conflicto de Interés (plantilla)", content: "" },
        { requirementCode: "9.1.4", templateType: "RECORD", name: "Evaluación del Cumplimiento de Obligaciones (plantilla)", content: "" },
        { requirementCode: "5.1.2", templateType: "RECORD", name: "Informe de Compliance al Órgano de Gobierno (plantilla)", content: "" },
      ],
    },
  ],
  /**
   * Estructura común del Anexo SL con ISO 9001 y solapes concretos: la
   * evaluación del cumplimiento legal ya existe en ISO 14001 y 45001, y los
   * controles de seguridad y proveedores en ISO 27001. Mapear evita duplicar
   * evidencias: un mismo elemento satisface requisitos de varias normas a través
   * de `RequirementCoverage`.
   */
  mappings: [
    { sourceFamily: "ISO_37301", sourceCode: "4.1", targetFamily: "ISO_9001", targetCode: "4.1", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37301", sourceCode: "4.2", targetFamily: "ISO_9001", targetCode: "4.2", relationType: "PARTIAL", equivalencePercent: 70, notes: "El SGC añade autoridades y reguladores como parte interesada central." },
    { sourceFamily: "ISO_37301", sourceCode: "5.2", targetFamily: "ISO_9001", targetCode: "5.2", relationType: "PARTIAL", equivalencePercent: 70, notes: "Política de compliance ⇄ política de calidad (misma estructura, alcance distinto)." },
    { sourceFamily: "ISO_37301", sourceCode: "7.5", targetFamily: "ISO_9001", targetCode: "7.5", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37301", sourceCode: "9.2", targetFamily: "ISO_9001", targetCode: "9.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37301", sourceCode: "9.3", targetFamily: "ISO_9001", targetCode: "9.3", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37301", sourceCode: "10.2", targetFamily: "ISO_9001", targetCode: "10.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37301", sourceCode: "6.3", targetFamily: "ISO_9001", targetCode: "6.3", relationType: "PARTIAL", equivalencePercent: 70, notes: "Cambios regulatorios ⇄ planificación de cambios." },
    { sourceFamily: "ISO_37301", sourceCode: "4.6", targetFamily: "ISO_14001", targetCode: "6.1.3", relationType: "PARTIAL", equivalencePercent: 70, notes: "Registro de obligaciones ⇄ requisitos legales y otros requisitos ambientales." },
    { sourceFamily: "ISO_37301", sourceCode: "9.1.4", targetFamily: "ISO_14001", targetCode: "9.1.2", relationType: "PARTIAL", equivalencePercent: 80, notes: "Evaluación del cumplimiento: misma mecánica, ámbito ambiental." },
    { sourceFamily: "ISO_37301", sourceCode: "4.6", targetFamily: "ISO_45001", targetCode: "6.1.3", relationType: "PARTIAL", equivalencePercent: 70, notes: "Obligaciones de compliance ⇄ requisitos legales de seguridad y salud." },
    { sourceFamily: "ISO_37301", sourceCode: "9.1.4", targetFamily: "ISO_45001", targetCode: "9.1.2", relationType: "PARTIAL", equivalencePercent: 80, notes: "Evaluación del cumplimiento legal en seguridad y salud." },
    { sourceFamily: "ISO_37301", sourceCode: "8.3", targetFamily: "ISO_45001", targetCode: "5.4", relationType: "RELATED", equivalencePercent: 50, notes: "Canal de denuncias ⇄ consulta y participación de los trabajadores (plantear preocupaciones sin represalias)." },
    { sourceFamily: "ISO_37301", sourceCode: "6.1", targetFamily: "ISO_27001", targetCode: "6.1.2", relationType: "PARTIAL", equivalencePercent: 60, notes: "Misma mecánica de valoración; el riesgo de compliance añade sanción y exposición reputacional." },
    { sourceFamily: "ISO_37301", sourceCode: "8.2", targetFamily: "ISO_27001", targetCode: "A.5", relationType: "RELATED", equivalencePercent: 60, notes: "Controles de compliance ⇄ controles organizacionales (se reutiliza el control ISO 27001 en lugar de duplicarlo)." },
    { sourceFamily: "ISO_37301", sourceCode: "8.3", targetFamily: "ISO_42001", targetCode: "A.3.3", relationType: "RELATED", equivalencePercent: 70, notes: "Canal de denuncias ⇄ reporte de preocupaciones sobre sistemas de IA: el mismo canal sirve para ambos." },
  ],
};
