import type { StandardPackInput } from "./pack-schema";

/**
 * ISO 37001:2016 — Sistema de Gestión Antisoborno (SGAS).
 *
 * Extensión del paquete de compliance (ISO 37301): no redefine obligaciones,
 * canal de denuncias, investigaciones genéricas ni CAPA. Los ids resuelven a
 * `req-iso-37001-<code>` vía `requirementIdFor`.
 *
 * Los requisitos de este pack apuntan a artefactos especializados
 * (terceros, debida diligencia, regalos, UBO, controles financieros) y
 * reutilizan el SGC para obligaciones, speak-up e investigación.
 */
export const iso37001Pack: StandardPackInput = {
  code: "PACK_ISO_37001",
  name: "ISO 37001 — Antisoborno",
  version: "2016.1",
  lifecycleStatus: "DEVELOPMENT",
  description: "Paquete normativo ISO 37001:2016 (Sistema de Gestión Antisoborno), extensión del SGC ISO 37301.",
  requiredModules: [
    "gap", "documents", "audits", "nonconformities", "actions", "indicators", "management-review", "training", "suppliers", "risks",
    "compliance", "speakup", "antibribery",
  ],
  featureFlags: {
    antiBriberyManagement: true,
    dueDiligence: true,
    giftHospitalityControls: true,
    beneficialOwnership: true,
  },
  editions: [
    {
      familyCode: "ISO_37001",
      familyName: "ISO 37001",
      category: "Compliance",
      familyDescription: "Sistema de Gestión Antisoborno",
      editionCode: "2016",
      name: "ISO 37001",
      version: "2016",
      year: 2016,
      description: "Sistema de Gestión Antisoborno (SGAS)",
      catalogVersion: "2016.1",
      status: "ACTIVE",
      requirements: [
        { code: "4", title: "Contexto de la organización" },
        { code: "4.1", title: "Comprensión de la organización y de su contexto", parent: "4" },
        { code: "4.2", title: "Comprensión de las necesidades y expectativas de las partes interesadas", parent: "4" },
        { code: "4.3", title: "Determinación del alcance del sistema de gestión antisoborno", parent: "4" },
        { code: "4.4", title: "Sistema de gestión antisoborno", parent: "4" },
        { code: "4.5", title: "Evaluación del riesgo de soborno", parent: "4", summary: "Valoración de riesgo de soborno con factores de país, sector, funcionario público y terceros." },
        { code: "5", title: "Liderazgo" },
        { code: "5.1", title: "Liderazgo y compromiso", parent: "5" },
        { code: "5.1.1", title: "Órgano de gobierno", parent: "5.1", summary: "Compromiso y supervisión del órgano de gobierno sobre el SGAS." },
        { code: "5.1.2", title: "Alta dirección", parent: "5.1" },
        { code: "5.2", title: "Política antisoborno", parent: "5" },
        { code: "5.3", title: "Roles, responsabilidades y autoridades", parent: "5" },
        { code: "5.3.1", title: "Roles y responsabilidades", parent: "5.3" },
        { code: "5.3.2", title: "Función de cumplimiento antisoborno", parent: "5.3", summary: "Independencia y autoridad de la función de cumplimiento antisoborno." },
        { code: "5.3.3", title: "Delegación de toma de decisiones", parent: "5.3", summary: "Aprobaciones de operaciones de alto riesgo con segregación de quien solicita y quien aprueba." },
        { code: "6", title: "Planificación" },
        { code: "6.1", title: "Acciones para abordar riesgos y oportunidades", parent: "6" },
        { code: "6.2", title: "Objetivos antisoborno y planificación para lograrlos", parent: "6" },
        { code: "7", title: "Apoyo" },
        { code: "7.1", title: "Recursos", parent: "7" },
        { code: "7.2", title: "Competencia", parent: "7" },
        { code: "7.2.1", title: "Generalidades", parent: "7.2" },
        { code: "7.2.2", title: "Proceso de empleo", parent: "7.2", summary: "Debida diligencia de personas, declaraciones de conflicto y compromisos antisoborno." },
        { code: "7.3", title: "Toma de conciencia y formación", parent: "7" },
        { code: "7.4", title: "Comunicación", parent: "7" },
        { code: "7.5", title: "Información documentada", parent: "7" },
        { code: "8", title: "Operación" },
        { code: "8.1", title: "Planificación y control operacional", parent: "8" },
        { code: "8.2", title: "Debida diligencia", parent: "8", summary: "Debida diligencia de socios de negocio: DRAFT→SCREENING→REVIEW→ENHANCED_REVIEW→APPROVED|REJECTED→PERIODIC_REVIEW." },
        { code: "8.3", title: "Controles financieros", parent: "8", summary: "Pruebas de diseño y eficacia operativa de controles financieros antisoborno." },
        { code: "8.4", title: "Controles no financieros", parent: "8", summary: "Controles de compras, contratos, personal y operaciones no financieras." },
        { code: "8.5", title: "Implementación de controles antisoborno por organizaciones controladas y por socios de negocio", parent: "8" },
        { code: "8.6", title: "Compromisos antisoborno", parent: "8", summary: "Compromisos documentados de personal y socios de negocio." },
        { code: "8.7", title: "Regalos, hospitalidad, donaciones y beneficios similares", parent: "8", summary: "Regalos/hospitalidad con flujo SUBMITTED→MANAGER_REVIEW→COMPLIANCE_REVIEW→APPROVED|REJECTED; donaciones y patrocinios." },
        { code: "8.8", title: "Gestión de la insuficiencia de controles antisoborno", parent: "8" },
        { code: "8.9", title: "Planteamiento de preocupaciones", parent: "8", summary: "Reutiliza el canal de denuncias del SGC (ISO 37301 §8.3); no se duplica." },
        { code: "8.10", title: "Investigación y tratamiento del soborno", parent: "8", summary: "Puente a Investigation del SGC con tipología antisoborno; no se reinventan evidencias ni independencia." },
        { code: "9", title: "Evaluación del desempeño" },
        { code: "9.1", title: "Seguimiento, medición, análisis y evaluación", parent: "9" },
        { code: "9.2", title: "Auditoría interna", parent: "9" },
        { code: "9.3", title: "Revisión por la dirección", parent: "9" },
        { code: "9.4", title: "Revisión por la función de cumplimiento antisoborno", parent: "9" },
        { code: "10", title: "Mejora" },
        { code: "10.1", title: "No conformidad y acción correctiva", parent: "10", summary: "Remediación y CAPA reutilizadas del SGC / CAPA corporativo." },
        { code: "10.2", title: "Mejora continua", parent: "10" },

        { code: "A", title: "Anexo A — Guía" },
        { code: "A.4", title: "Evaluación del riesgo de soborno", parent: "A" },
        { code: "A.4.5", title: "Factores de riesgo de soborno", parent: "A.4", summary: "País, sector, funcionario público, terceros y beneficiario final." },
        { code: "A.8", title: "Controles operativos", parent: "A" },
        { code: "A.8.2", title: "Debida diligencia de socios de negocio", parent: "A.8" },
        { code: "A.8.3", title: "Controles financieros", parent: "A.8" },
        { code: "A.8.4", title: "Controles no financieros", parent: "A.8" },
        { code: "A.8.7", title: "Regalos, hospitalidad y donaciones", parent: "A.8" },
        { code: "A.8.9", title: "Canal de denuncias (reutilizado)", parent: "A.8" },
        { code: "A.8.10", title: "Investigación de soborno", parent: "A.8" },
      ],
      evidenceRules: [
        { requirementCode: "4.5", expectedType: "RECORD", frequency: "ANNUAL", note: "Evaluaciones de riesgo de soborno con nivel inherente, residual y aprobación." },
        { requirementCode: "5.2", expectedType: "POLICY", frequency: "ANNUAL", note: "Política antisoborno aprobada." },
        { requirementCode: "7.2.2", expectedType: "RECORD", frequency: "ANNUAL", note: "Declaraciones de conflicto ABMS y compromisos del personal expuesto." },
        { requirementCode: "8.2", expectedType: "RECORD", frequency: "ANNUAL", note: "Expedientes de debida diligencia de socios de negocio con screening y decisión." },
        { requirementCode: "8.3", expectedType: "RECORD", frequency: "QUARTERLY", note: "Pruebas de controles financieros antisoborno." },
        { requirementCode: "8.4", expectedType: "RECORD", frequency: "QUARTERLY", note: "Pruebas de controles no financieros antisoborno." },
        { requirementCode: "8.6", expectedType: "RECORD", frequency: "ANNUAL", note: "Compromisos antisoborno firmados por personal y socios." },
        { requirementCode: "8.7", expectedType: "RECORD", frequency: "QUARTERLY", note: "Registro de regalos, hospitalidad, donaciones y patrocinios con decisión." },
        { requirementCode: "8.9", expectedType: "PROCEDURE", frequency: "ANNUAL", note: "Canal de denuncias del SGC habilitado para alegaciones de soborno." },
        { requirementCode: "8.10", expectedType: "RECORD", retentionMonths: 60, note: "Investigaciones de soborno enlazadas a Investigation del SGC." },
      ],
      gapQuestions: [
        { requirementCode: "4.5", question: "¿Existe una evaluación de riesgo de soborno con factores de país, sector y funcionario público?", weight: 3 },
        { requirementCode: "8.2", question: "¿Los socios de negocio de riesgo alto pasan por debida diligencia reforzada antes de contratar?", guidance: "Flujo con SCREENING, REVIEW y ENHANCED_REVIEW documentados.", weight: 3 },
        { requirementCode: "A.4.5", question: "¿Se identifica al beneficiario final (UBO) de los terceros de riesgo?", weight: 3 },
        { requirementCode: "8.7", question: "¿Los regalos y la hospitalidad por encima del umbral o con funcionario público pasan por compliance?", weight: 3 },
        { requirementCode: "8.3", question: "¿Se prueban periódicamente los controles financieros antisoborno?", weight: 2 },
        { requirementCode: "8.4", question: "¿Se prueban controles no financieros (compras, contratos, personal)?", weight: 2 },
        { requirementCode: "5.3.3", question: "¿Las operaciones de alto riesgo tienen aprobación independiente de quien las solicita?", weight: 3 },
        { requirementCode: "8.6", question: "¿Personal y socios de negocio documentan su compromiso antisoborno?", weight: 2 },
        { requirementCode: "8.9", question: "¿Las alegaciones de soborno se canalizan por el speak-up del SGC sin duplicar el canal?", weight: 2 },
        { requirementCode: "8.10", question: "¿Las investigaciones de soborno reutilizan Investigation del SGC con tipología ABMS?", weight: 3 },
      ],
      auditChecklist: [
        { requirementCode: "4.5", question: "Revisar el mapa de riesgo de soborno.", expectedEvidence: "Evaluaciones con uplift de país/sector/PEP y aprobación.", criterion: "Las evaluaciones aprobadas tienen aprobador y fecha." },
        { requirementCode: "8.2", question: "Verificar debida diligencia de un socio de riesgo alto.", expectedEvidence: "Expediente con screening, revisión reforzada y decisión.", criterion: "No hay APPROVED sin paso por REVIEW o ENHANCED_REVIEW cuando el riesgo lo exige." },
        { requirementCode: "A.4.5", question: "Comprobar identificación de beneficiarios finales.", expectedEvidence: "UBO con porcentaje/control y verificación.", criterion: "Terceros de riesgo alto con ownershipKnown o UBO registrado." },
        { requirementCode: "8.7", question: "Revisar regalos/hospitalidad con funcionario público.", expectedEvidence: "Registro con COMPLIANCE_REVIEW y decisión.", criterion: "Ninguna aprobación final sin revisor de compliance atribuido." },
        { requirementCode: "5.3.3", question: "Verificar segregación en operaciones de alto riesgo.", expectedEvidence: "Aprobaciones con solicitante ≠ aprobador.", criterion: "CHECK/regla de dominio impide auto-aprobación." },
        { requirementCode: "8.10", question: "Revisar investigaciones de soborno.", expectedEvidence: "AntiBriberyInvestigation enlazada a Investigation.", criterion: "No existe un segundo motor de investigación; el puente es obligatorio." },
      ],
      templates: [
        { requirementCode: "5.2", templateType: "POLICY", name: "Política Antisoborno (plantilla)", content: "" },
        { requirementCode: "4.5", templateType: "RECORD", name: "Evaluación de Riesgo de Soborno (plantilla)", content: "" },
        { requirementCode: "8.2", templateType: "PROCEDURE", name: "Procedimiento de Debida Diligencia de Terceros (plantilla)", content: "" },
        { requirementCode: "8.7", templateType: "PROCEDURE", name: "Procedimiento de Regalos, Hospitalidad y Donaciones (plantilla)", content: "" },
        { requirementCode: "8.6", templateType: "RECORD", name: "Compromiso Antisoborno (plantilla)", content: "" },
      ],
    },
  ],
  /**
   * Extiende 37301 (obligaciones, speak-up, investigación) y solapa Anexo SL
   * con 9001; controles financieros/no financieros con 27001; proveedores con
   * debida diligencia de terceros.
   */
  mappings: [
    { sourceFamily: "ISO_37001", sourceCode: "4.1", targetFamily: "ISO_37301", targetCode: "4.1", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37001", sourceCode: "4.2", targetFamily: "ISO_37301", targetCode: "4.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37001", sourceCode: "5.2", targetFamily: "ISO_37301", targetCode: "5.2", relationType: "PARTIAL", equivalencePercent: 70, notes: "Política antisoborno ⇄ política de compliance (alcance más estrecho)." },
    { sourceFamily: "ISO_37001", sourceCode: "5.3.2", targetFamily: "ISO_37301", targetCode: "5.3.1", relationType: "PARTIAL", equivalencePercent: 80, notes: "Función de cumplimiento antisoborno ⇄ función de compliance." },
    { sourceFamily: "ISO_37001", sourceCode: "4.5", targetFamily: "ISO_37301", targetCode: "6.1", relationType: "PARTIAL", equivalencePercent: 70, notes: "Riesgo de soborno especializa el riesgo de compliance; no duplica ComplianceRisk." },
    { sourceFamily: "ISO_37001", sourceCode: "8.9", targetFamily: "ISO_37301", targetCode: "8.3", relationType: "EQUIVALENT", equivalencePercent: 100, notes: "Mismo canal de denuncias; ABMS tipifica alegaciones de soborno." },
    { sourceFamily: "ISO_37001", sourceCode: "8.10", targetFamily: "ISO_37301", targetCode: "8.4", relationType: "EQUIVALENT", equivalencePercent: 100, notes: "Investigation del SGC + puente AntiBriberyInvestigation." },
    { sourceFamily: "ISO_37001", sourceCode: "10.1", targetFamily: "ISO_37301", targetCode: "10.2", relationType: "EQUIVALENT", equivalencePercent: 100, notes: "Remediación/CAPA del SGC." },
    { sourceFamily: "ISO_37001", sourceCode: "7.5", targetFamily: "ISO_9001", targetCode: "7.5", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37001", sourceCode: "9.2", targetFamily: "ISO_9001", targetCode: "9.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37001", sourceCode: "9.3", targetFamily: "ISO_9001", targetCode: "9.3", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_37001", sourceCode: "8.2", targetFamily: "ISO_27001", targetCode: "A.5", relationType: "RELATED", equivalencePercent: 50, notes: "Debida diligencia de terceros ⇄ controles organizacionales / proveedores." },
    { sourceFamily: "ISO_37001", sourceCode: "8.3", targetFamily: "ISO_27001", targetCode: "A.5", relationType: "RELATED", equivalencePercent: 40, notes: "Puede reutilizar OrganizationControl; la prueba ABMS es el artefacto especializado." },
    { sourceFamily: "ISO_37001", sourceCode: "8.9", targetFamily: "ISO_42001", targetCode: "A.3.3", relationType: "RELATED", equivalencePercent: 60, notes: "Mismo canal speak-up para preocupaciones de soborno e IA." },
  ],
};
