import type { StandardPackInput } from "./pack-schema";

/**
 * ISO 22000:2018 — Sistema de Gestión de la Inocuidad de los Alimentos (SGIA / FSMS)
 * + principios HACCP. Títulos y resúmenes propios de NormaFlow — nunca el texto protegido.
 */
export const iso22000Pack: StandardPackInput = {
  code: "PACK_ISO_22000",
  name: "ISO 22000 — Inocuidad alimentaria",
  version: "2018.1",
  description: "Paquete normativo ISO 22000:2018 (SGIA) con PRP, OPRP, PCC, monitoreo, trazabilidad y retiro.",
  requiredModules: [
    "gap", "documents", "audits", "nc", "capa", "indicators", "mgmt-review", "suppliers", "food-safety",
  ],
  featureFlags: { foodSafetyManagement: true, haccp: true, traceability: true },
  editions: [
    {
      familyCode: "ISO_22000",
      familyName: "ISO 22000",
      category: "Inocuidad alimentaria",
      familyDescription: "Sistema de Gestión de la Inocuidad de los Alimentos",
      editionCode: "2018",
      name: "ISO 22000",
      version: "2018",
      year: 2018,
      description: "Sistema de Gestión de la Inocuidad de los Alimentos (SGIA)",
      catalogVersion: "2018.1",
      status: "ACTIVE",
      requirements: [
        { code: "4", title: "Contexto de la organización" },
        { code: "4.1", title: "Comprensión de la organización y de su contexto", parent: "4" },
        { code: "4.2", title: "Comprensión de las necesidades y expectativas de las partes interesadas", parent: "4" },
        { code: "4.3", title: "Determinación del alcance del sistema de gestión de la inocuidad de los alimentos", parent: "4" },
        { code: "4.4", title: "Sistema de gestión de la inocuidad de los alimentos", parent: "4" },
        { code: "5", title: "Liderazgo" },
        { code: "5.1", title: "Liderazgo y compromiso", parent: "5" },
        { code: "5.2", title: "Política", parent: "5" },
        { code: "5.3", title: "Roles, responsabilidades y autoridades en la organización", parent: "5" },
        { code: "6", title: "Planificación" },
        { code: "6.1", title: "Acciones para abordar riesgos y oportunidades", parent: "6" },
        { code: "6.2", title: "Objetivos del sistema de gestión de la inocuidad de los alimentos y planificación para lograrlos", parent: "6" },
        { code: "6.3", title: "Planificación de los cambios", parent: "6" },
        { code: "7", title: "Apoyo" },
        { code: "7.1", title: "Recursos", parent: "7" },
        { code: "7.2", title: "Competencia", parent: "7" },
        { code: "7.3", title: "Toma de conciencia", parent: "7" },
        { code: "7.4", title: "Comunicación", parent: "7" },
        { code: "7.5", title: "Información documentada", parent: "7" },
        { code: "8", title: "Operación" },
        { code: "8.1", title: "Planificación y control operacional", parent: "8" },
        { code: "8.2", title: "Programas de prerrequisitos (PRP)", parent: "8", summary: "PRP: higiene, plagas, agua, limpieza, personal, proveedores, alérgenos, etc." },
        { code: "8.3", title: "Sistema de trazabilidad", parent: "8", summary: "Lotes de materia prima → proceso → producto terminado → cliente/distribución; prueba adelante/atrás." },
        { code: "8.4", title: "Preparación y respuesta ante emergencias", parent: "8" },
        { code: "8.5", title: "Control de peligros", parent: "8", summary: "Análisis de peligros, OPRP, PCC, límites críticos, monitoreo, correcciones y acciones correctivas." },
        { code: "8.5.1", title: "Análisis de peligros", parent: "8.5" },
        { code: "8.5.2", title: "Validación de medidas de control y combinaciones de medidas de control", parent: "8.5" },
        { code: "8.5.3", title: "Plan de control de peligros (PCC/OPRP)", parent: "8.5" },
        { code: "8.5.4", title: "Control de monitoreo y medición", parent: "8.5" },
        { code: "8.6", title: "Actualización de la información que especifica los PRP y el plan de control de peligros", parent: "8" },
        { code: "8.7", title: "Control del monitoreo y la medición", parent: "8" },
        { code: "8.8", title: "Verificación relacionada con los PRP y el plan de control de peligros", parent: "8" },
        { code: "8.9", title: "Control de las no conformidades del producto y del proceso", parent: "8", summary: "Desviaciones, correcciones, retención de producto y retiros/recalls." },
        { code: "9", title: "Evaluación del desempeño" },
        { code: "9.1", title: "Seguimiento, medición, análisis y evaluación", parent: "9" },
        { code: "9.2", title: "Auditoría interna", parent: "9" },
        { code: "9.3", title: "Revisión por la dirección", parent: "9" },
        { code: "10", title: "Mejora" },
        { code: "10.1", title: "No conformidad y acción correctiva", parent: "10" },
        { code: "10.2", title: "Actualización continua del sistema de gestión de la inocuidad de los alimentos", parent: "10" },
        { code: "10.3", title: "Mejora continua", parent: "10" },
      ],
      evidenceRules: [
        { requirementCode: "8.2", expectedType: "RECORD", frequency: "ANNUAL", note: "PRP documentados y evidenciados." },
        { requirementCode: "8.3", expectedType: "RECORD", note: "Registros de lote y prueba de trazabilidad adelante/atrás." },
        { requirementCode: "8.5.1", expectedType: "RECORD", note: "Análisis de peligros con severidad, probabilidad y decisión de control." },
        { requirementCode: "8.5.3", expectedType: "RECORD", note: "Plan PCC/OPRP con límites críticos y monitoreo." },
        { requirementCode: "8.5.2", expectedType: "RECORD", note: "Validación de medidas de control." },
        { requirementCode: "8.8", expectedType: "RECORD", frequency: "ANNUAL", note: "Actividades de verificación." },
        { requirementCode: "8.9", expectedType: "RECORD", note: "Desviaciones, correcciones y retiros cuando aplique." },
        { requirementCode: "8.4", expectedType: "RECORD", note: "Registro de emergencias de inocuidad." },
      ],
      gapQuestions: [
        { requirementCode: "8.2", question: "¿Existen PRP documentados (higiene, plagas, limpieza, alérgenos, etc.)?", weight: 3 },
        { requirementCode: "8.5.1", question: "¿Se evaluaron peligros biológicos, químicos, físicos y de alérgenos por etapa?", weight: 3 },
        { requirementCode: "8.5.3", question: "¿Cada PCC tiene límite crítico, plan de monitoreo y corrección definida?", weight: 3 },
        { requirementCode: "8.3", question: "¿Se puede reconstruir la trazabilidad hacia atrás (proveedor) y hacia adelante (cliente)?", weight: 3 },
        { requirementCode: "8.9", question: "¿Hay procedimiento de retiro/recall ensayado o documentado?", weight: 3 },
        { requirementCode: "8.8", question: "¿Se realizan actividades de verificación del plan HACCP/PRP?", weight: 2 },
        { requirementCode: "8.4", question: "¿Hay preparación ante emergencias de inocuidad?", weight: 2 },
      ],
      auditChecklist: [
        { requirementCode: "8.5.1", question: "Muestrear evaluaciones de peligros significativos y su decisión PRP/OPRP/CCP.", expectedEvidence: "HazardAssessment con score y controlDecision.", criterion: "Significativos con decisión justificada." },
        { requirementCode: "8.5.3", question: "Verificar un PCC con límites y registros de monitoreo.", expectedEvidence: "CCP + CriticalLimit + MonitoringRecord.", criterion: "Fuera de límite abre desviación o corrección." },
        { requirementCode: "8.3", question: "Ejecutar prueba de trazabilidad adelante y atrás sobre un lote terminado.", expectedEvidence: "Cadena de TraceabilityLot con previousLotIds.", criterion: "Cadena completa proveedor→cliente." },
        { requirementCode: "8.9", question: "Revisar un retiro o ensayo de recall.", expectedEvidence: "WithdrawalRecall con lotes afectados.", criterion: "Lotes marcados y notificación registrada." },
        { requirementCode: "8.2", question: "Comprobar PRP de control de alérgenos y vínculo a productos/MP.", expectedEvidence: "Allergen + allergenCodes en producto/MP.", criterion: "Alérgenos declarados y controlados." },
      ],
      templates: [
        { requirementCode: "5.2", templateType: "POLICY", name: "Política de Inocuidad Alimentaria (plantilla)", content: "" },
        { requirementCode: "8.5.1", templateType: "RECORD", name: "Análisis de peligros HACCP (plantilla)", content: "" },
        { requirementCode: "8.5.3", templateType: "RECORD", name: "Plan de PCC / OPRP (plantilla)", content: "" },
        { requirementCode: "8.3", templateType: "RECORD", name: "Prueba de trazabilidad (plantilla)", content: "" },
        { requirementCode: "8.9", templateType: "RECORD", name: "Retiro / recall (plantilla)", content: "" },
      ],
    },
  ],
  mappings: [
    { sourceFamily: "ISO_22000", sourceCode: "4.1", targetFamily: "ISO_9001", targetCode: "4.1", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_22000", sourceCode: "5.2", targetFamily: "ISO_9001", targetCode: "5.2", relationType: "PARTIAL", equivalencePercent: 70, notes: "Política de inocuidad ⇄ política de calidad." },
    { sourceFamily: "ISO_22000", sourceCode: "7.5", targetFamily: "ISO_9001", targetCode: "7.5", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_22000", sourceCode: "9.2", targetFamily: "ISO_9001", targetCode: "9.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_22000", sourceCode: "9.3", targetFamily: "ISO_9001", targetCode: "9.3", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_22000", sourceCode: "10.1", targetFamily: "ISO_9001", targetCode: "10.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_22000", sourceCode: "8.2", targetFamily: "ISO_14001", targetCode: "8.1", relationType: "RELATED", equivalencePercent: 30, notes: "PRP operativos ⇄ control operacional ambiental (perspectiva distinta)." },
    { sourceFamily: "ISO_22000", sourceCode: "8.4", targetFamily: "ISO_45001", targetCode: "8.2", relationType: "RELATED", equivalencePercent: 40, notes: "Emergencias de inocuidad ⇄ preparación ante emergencias SST (ámbitos distintos)." },
    { sourceFamily: "ISO_22000", sourceCode: "8.5.1", targetFamily: "ISO_45001", targetCode: "6.1.2", relationType: "RELATED", equivalencePercent: 35, notes: "Análisis de peligros alimentarios ⇄ identificación de peligros SST; modelos separados." },
  ],
};
