import type { StandardPackInput } from "./pack-schema";

/**
 * ISO/IEC 20000-1:2018 — Sistema de Gestión de Servicios de TI (SGSTI / ITSM).
 * Títulos y resúmenes propios de NormaFlow — nunca el texto protegido.
 * Incidentes de servicio = ITSMIncident (no SecurityIncident ISO 27001).
 */
export const iso20000Pack: StandardPackInput = {
  code: "PACK_ISO_20000",
  name: "ISO/IEC 20000 — Gestión de servicios TI",
  version: "2018.1",
  description: "Paquete normativo ISO/IEC 20000-1:2018 (ITSM): catálogo, SLA, incidentes, problemas, cambios, CMDB, disponibilidad, capacidad y continuidad de servicio.",
  requiredModules: [
    "gap", "documents", "audits", "nc", "capa", "indicators", "mgmt-review", "suppliers", "itsm",
  ],
  featureFlags: { itsm: true, serviceCatalog: true, cmdb: true },
  editions: [
    {
      familyCode: "ISO_20000",
      familyName: "ISO/IEC 20000",
      category: "Servicios TI",
      familyDescription: "Sistema de Gestión de Servicios de TI",
      editionCode: "2018",
      name: "ISO/IEC 20000-1",
      version: "2018",
      year: 2018,
      description: "Requisitos del sistema de gestión de servicios",
      catalogVersion: "2018.1",
      status: "ACTIVE",
      requirements: [
        { code: "4", title: "Contexto de la organización" },
        { code: "4.1", title: "Comprensión de la organización y de su contexto", parent: "4" },
        { code: "4.2", title: "Comprensión de las necesidades y expectativas de las partes interesadas", parent: "4" },
        { code: "4.3", title: "Determinación del alcance del sistema de gestión de servicios", parent: "4" },
        { code: "4.4", title: "Sistema de gestión de servicios", parent: "4" },
        { code: "5", title: "Liderazgo" },
        { code: "5.1", title: "Liderazgo y compromiso", parent: "5" },
        { code: "5.2", title: "Política", parent: "5" },
        { code: "5.3", title: "Roles, responsabilidades y autoridades en la organización", parent: "5" },
        { code: "6", title: "Planificación" },
        { code: "6.1", title: "Acciones para abordar riesgos y oportunidades", parent: "6" },
        { code: "6.2", title: "Objetivos del servicio y planificación para lograrlos", parent: "6" },
        { code: "6.3", title: "Planificación de los cambios del SGSTI", parent: "6" },
        { code: "7", title: "Apoyo" },
        { code: "7.1", title: "Recursos", parent: "7" },
        { code: "7.2", title: "Competencia", parent: "7" },
        { code: "7.3", title: "Toma de conciencia", parent: "7" },
        { code: "7.4", title: "Comunicación", parent: "7" },
        { code: "7.5", title: "Información documentada", parent: "7" },
        { code: "7.6", title: "Conocimiento", parent: "7", summary: "Base de conocimiento y errores conocidos." },
        { code: "8", title: "Operación" },
        { code: "8.1", title: "Planificación y control operacional", parent: "8" },
        { code: "8.2", title: "Portfolio de servicios", parent: "8", summary: "Catálogo de servicios y propietarios." },
        { code: "8.3", title: "Relación y acuerdo", parent: "8", summary: "SLA, OLA y proveedores de servicio." },
        { code: "8.4", title: "Oferta y demanda", parent: "8" },
        { code: "8.5", title: "Diseño, construcción y transición del servicio", parent: "8", summary: "Cambios, releases y despliegues." },
        { code: "8.6", title: "Resolución y cumplimiento", parent: "8", summary: "Solicitudes, incidentes ITSM, problemas y errores conocidos." },
        { code: "8.7", title: "Aseguramiento del servicio", parent: "8", summary: "Disponibilidad, capacidad, continuidad de servicio y CMDB." },
        { code: "9", title: "Evaluación del desempeño" },
        { code: "9.1", title: "Seguimiento, medición, análisis y evaluación", parent: "9", summary: "Informes de desempeño del servicio y cumplimiento de SLA." },
        { code: "9.2", title: "Auditoría interna", parent: "9" },
        { code: "9.3", title: "Revisión por la dirección", parent: "9" },
        { code: "10", title: "Mejora" },
        { code: "10.1", title: "No conformidad y acción correctiva", parent: "10" },
        { code: "10.2", title: "Mejora continua", parent: "10" },
      ],
      evidenceRules: [
        { requirementCode: "8.2", expectedType: "RECORD", note: "Catálogo de servicios y propietarios." },
        { requirementCode: "8.3", expectedType: "RECORD", frequency: "ANNUAL", note: "SLA/OLA activos y revisiones de proveedores." },
        { requirementCode: "8.5", expectedType: "RECORD", note: "Cambios, releases y despliegues con aprobación." },
        { requirementCode: "8.6", expectedType: "RECORD", note: "Incidentes ITSM, problemas y errores conocidos." },
        { requirementCode: "8.7", expectedType: "RECORD", frequency: "ANNUAL", note: "Planes de disponibilidad, capacidad, continuidad y CMDB." },
        { requirementCode: "7.6", expectedType: "RECORD", note: "Artículos de conocimiento publicados." },
        { requirementCode: "9.1", expectedType: "REPORT", frequency: "MONTHLY", note: "Informes de desempeño y cumplimiento de SLA." },
      ],
      gapQuestions: [
        { requirementCode: "8.2", question: "¿Existe un catálogo de servicios con propietario asignado?", weight: 3 },
        { requirementCode: "8.3", question: "¿Hay SLA con tiempos de respuesta y resolución medibles?", weight: 3 },
        { requirementCode: "8.6", question: "¿Los incidentes de servicio siguen NEW→…→CLOSED y se distinguen de incidentes de seguridad?", weight: 3 },
        { requirementCode: "8.6", question: "¿Los problemas pueden convertirse en errores conocidos con workaround?", weight: 2 },
        { requirementCode: "8.5", question: "¿Los cambios requieren evaluación y aprobación antes de implementarse?", weight: 3 },
        { requirementCode: "8.7", question: "¿Hay CMDB con relaciones entre CIs y planes de disponibilidad/capacidad/continuidad?", weight: 3 },
        { requirementCode: "9.1", question: "¿Se reporta el desempeño del servicio (SLA, MTTR, disponibilidad)?", weight: 2 },
      ],
      auditChecklist: [
        { requirementCode: "8.3", question: "Muestrear un SLA activo y verificar tiempos.", expectedEvidence: "ServiceLevelAgreement ACTIVE.", criterion: "Respuesta y resolución > 0." },
        { requirementCode: "8.6", question: "Revisar un incidente ITSM cerrado con confirmación.", expectedEvidence: "ITSMIncident CLOSED con confirmedById/resolvedAt.", criterion: "No usar SecurityIncident para fallos de servicio." },
        { requirementCode: "8.6", question: "Verificar un problema en KNOWN_ERROR con KnownError vinculado.", expectedEvidence: "Problem + KnownError + workaround.", criterion: "Transiciones del workflow respetadas." },
        { requirementCode: "8.5", question: "Revisar un cambio APPROVED/IMPLEMENTED con aprobador.", expectedEvidence: "ITSMChange con approvedById.", criterion: "Distinto de ChangeRequest de gestión del cambio ISO." },
        { requirementCode: "8.7", question: "Comprobar CIs relacionados y un plan de disponibilidad.", expectedEvidence: "ConfigurationItem + CMDBRelationship + AvailabilityPlan.", criterion: "Sin auto-relación; % disponibilidad coherente." },
      ],
      templates: [
        { requirementCode: "5.2", templateType: "POLICY", name: "Política de Gestión de Servicios TI (plantilla)", content: "" },
        { requirementCode: "8.3", templateType: "RECORD", name: "Acuerdo de Nivel de Servicio — SLA (plantilla)", content: "" },
        { requirementCode: "8.6", templateType: "RECORD", name: "Registro de incidente de servicio (plantilla)", content: "" },
        { requirementCode: "8.5", templateType: "RECORD", name: "Solicitud de cambio ITSM (plantilla)", content: "" },
        { requirementCode: "9.1", templateType: "RECORD", name: "Informe de desempeño del servicio (plantilla)", content: "" },
      ],
    },
  ],
  mappings: [
    { sourceFamily: "ISO_20000", sourceCode: "4.1", targetFamily: "ISO_9001", targetCode: "4.1", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_20000", sourceCode: "5.2", targetFamily: "ISO_9001", targetCode: "5.2", relationType: "PARTIAL", equivalencePercent: 70, notes: "Política de servicio ⇄ política de calidad." },
    { sourceFamily: "ISO_20000", sourceCode: "7.5", targetFamily: "ISO_9001", targetCode: "7.5", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_20000", sourceCode: "9.2", targetFamily: "ISO_9001", targetCode: "9.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_20000", sourceCode: "9.3", targetFamily: "ISO_9001", targetCode: "9.3", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_20000", sourceCode: "10.1", targetFamily: "ISO_9001", targetCode: "10.2", relationType: "EQUIVALENT", equivalencePercent: 100 },
    { sourceFamily: "ISO_20000", sourceCode: "8.6", targetFamily: "ISO_27001", targetCode: "A.5", relationType: "RELATED", equivalencePercent: 30, notes: "Incidentes de servicio (ITSMIncident) ⇄ controles organizacionales / incidentes de seguridad (SecurityIncident); modelos separados." },
    { sourceFamily: "ISO_20000", sourceCode: "8.7", targetFamily: "ISO_9001", targetCode: "8.2", relationType: "RELATED", equivalencePercent: 35, notes: "Aseguramiento del servicio (disponibilidad/capacidad/continuidad) ⇄ requisitos para productos y servicios; BCP corporativo se enlaza por bcpId." },
    { sourceFamily: "ISO_20000", sourceCode: "8.5", targetFamily: "ISO_9001", targetCode: "8.5.6", relationType: "RELATED", equivalencePercent: 45, notes: "ITSMChange ⇄ control de cambios de producto/servicio; distinto de ChangeRequest corporativo." },
  ],
};
