-- ISO 37001: beneficial owners (UBO) are real named third parties, including
-- PEP status — the same class of sensitive personal data as occupational
-- health surveillance or medical device vigilance. It was gated on the
-- generic "compliance:*" permission (same bucket as risk assessments, due
-- diligence, gifts) — meaning any role with compliance:read, including
-- CONTRIBUTOR-adjacent reporting roles, could read UBO/PEP data. Reinforce
-- it exactly like the safety-sensitive / md-sensitive precedent: a
-- dedicated permission, not granted to CONTRIBUTOR/VIEWER, RLS-enforced.

DROP POLICY IF EXISTS "nf_beneficial_owners_select" ON "beneficial_owners";
DROP POLICY IF EXISTS "nf_beneficial_owners_insert" ON "beneficial_owners";
DROP POLICY IF EXISTS "nf_beneficial_owners_update" ON "beneficial_owners";
DROP POLICY IF EXISTS "nf_beneficial_owners_delete" ON "beneficial_owners";

CREATE POLICY "nf_beneficial_owners_select" ON "beneficial_owners"
  FOR SELECT TO authenticated USING (public.nf_has_org_permission("organizationId", 'antibribery-sensitive:read'));
CREATE POLICY "nf_beneficial_owners_insert" ON "beneficial_owners"
  FOR INSERT TO authenticated WITH CHECK (public.nf_has_org_permission("organizationId", 'antibribery-sensitive:create'));
CREATE POLICY "nf_beneficial_owners_update" ON "beneficial_owners"
  FOR UPDATE TO authenticated USING (public.nf_has_org_permission("organizationId", 'antibribery-sensitive:update')) WITH CHECK (public.nf_has_org_permission("organizationId", 'antibribery-sensitive:update'));
CREATE POLICY "nf_beneficial_owners_delete" ON "beneficial_owners"
  FOR DELETE TO authenticated USING (public.nf_has_org_permission("organizationId", 'antibribery-sensitive:delete'));

-- ─── ROLE PERMISSIONS (Supabase direct-authorization mirror) ─
-- Keep in sync with src/lib/permissions/matrix.ts. Base copied verbatim from
-- 20260725040000_safety_sensitive_privacy (the latest prior redefinition)
-- plus antibribery-sensitive:* appended — NOT granted to CONTRIBUTOR or VIEWER.
CREATE OR REPLACE FUNCTION public.nf_role_permissions(app_role "Role") RETURNS TEXT[] LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE app_role
    WHEN 'SUPER_ADMIN'::"Role" THEN ARRAY['*']::TEXT[]
    WHEN 'OWNER'::"Role" THEN ARRAY['*']::TEXT[]
    WHEN 'ORG_ADMIN'::"Role" THEN ARRAY['dashboard:read', 'notifications:read', 'org:*', 'members:*', 'groups:*', 'documents:*', 'processes:*', 'evidence:*', 'records:*', 'risks:*', 'audits:*', 'audit-program:*', 'nc:*', 'actions:*', 'indicators:*', 'gap:*', 'training:*', 'changes:*', 'suppliers:*', 'opportunities:*', 'integrations:*', 'reporting:*', 'activity:*', 'positions:*', 'personnel:*', 'locations:*', 'catalogs:*', 'mgmt-review:*', 'billing:*', 'security-controls:*', 'soa:*', 'risk-treatment:*', 'assets:*', 'incidents:*', 'vulnerabilities:*', 'continuity:*', 'standards:*', 'environment:*', 'safety:*', 'integrated:*', 'aims:*', 'compliance:*', 'speakup:create', 'energy:*', 'food-safety:*', 'itsm:*', 'medical-devices:*', 'md-sensitive:*', 'quality-ops:*', 'design-dev:*', 'safety-sensitive:*', 'antibribery-sensitive:*']::TEXT[]
    WHEN 'MANAGER'::"Role" THEN ARRAY['dashboard:view', 'notifications:view', 'documents:*', 'processes:*', 'evidence:*', 'records:*', 'risks:*', 'audits:*', 'audit-program:*', 'nc:*', 'actions:*', 'indicators:*', 'gap:*', 'training:*', 'changes:*', 'suppliers:*', 'opportunities:*', 'integrations:view', 'reporting:*', 'activity:view', 'positions:view', 'personnel:view', 'locations:view', 'catalogs:view', 'mgmt-review:*', 'groups:view', 'security-controls:*', 'soa:*', 'risk-treatment:*', 'assets:*', 'incidents:*', 'vulnerabilities:*', 'continuity:*', 'standards:read', 'standards:activate', 'environment:*', 'safety:*', 'integrated:*', 'aims:*', 'compliance:*', 'speakup:create', 'energy:*', 'food-safety:*', 'itsm:*', 'medical-devices:*', 'md-sensitive:*', 'quality-ops:*', 'design-dev:*', 'safety-sensitive:*', 'antibribery-sensitive:*']::TEXT[]
    WHEN 'COMPLIANCE_MANAGER'::"Role" THEN ARRAY['dashboard:read', 'notifications:read', 'documents:*', 'processes:*', 'evidence:*', 'records:*', 'risks:*', 'audits:*', 'audit-program:*', 'nc:*', 'actions:*', 'indicators:*', 'gap:*', 'training:*', 'changes:*', 'suppliers:*', 'opportunities:*', 'integrations:read', 'integrations:manage', 'reporting:*', 'activity:read', 'positions:read', 'personnel:read', 'locations:read', 'catalogs:read', 'mgmt-review:*', 'groups:read', 'security-controls:*', 'soa:*', 'risk-treatment:*', 'assets:*', 'incidents:*', 'vulnerabilities:*', 'continuity:*', 'standards:*', 'environment:*', 'safety:*', 'integrated:*', 'aims:*', 'compliance:*', 'speakup:read', 'speakup:create', 'speakup:update', 'speakup:approve', 'speakup:export', 'energy:*', 'food-safety:*', 'itsm:*', 'medical-devices:*', 'md-sensitive:*', 'quality-ops:*', 'design-dev:*', 'safety-sensitive:*', 'antibribery-sensitive:*']::TEXT[]
    WHEN 'AUDITOR'::"Role" THEN ARRAY['dashboard:read', 'notifications:read', 'audits:*', 'audit-program:read', 'audit-program:export', 'audits:export', 'nc:create', 'nc:read', 'documents:read', 'processes:read', 'evidence:read', 'records:read', 'records:export', 'risks:read', 'training:read', 'changes:read', 'suppliers:read', 'suppliers:export', 'opportunities:read', 'documents:approve', 'documents:export', 'actions:read', 'actions:create', 'actions:export', 'evidence:export', 'reporting:export', 'reporting:read', 'activity:read', 'personnel:read', 'positions:read', 'catalogs:read', 'mgmt-review:read', 'mgmt-review:export', 'security-controls:read', 'security-controls:export', 'security-controls:approve', 'soa:read', 'soa:export', 'soa:approve', 'risk-treatment:read', 'risk-treatment:export', 'assets:read', 'assets:export', 'incidents:read', 'incidents:export', 'vulnerabilities:read', 'vulnerabilities:export', 'continuity:read', 'continuity:export', 'standards:read', 'environment:read', 'environment:export', 'safety:read', 'safety:export', 'integrated:read', 'integrated:export', 'aims:read', 'aims:export', 'compliance:read', 'compliance:export', 'speakup:create', 'energy:read', 'energy:export', 'food-safety:read', 'food-safety:export', 'itsm:read', 'itsm:export', 'medical-devices:read', 'medical-devices:export', 'md-sensitive:read', 'md-sensitive:export', 'quality-ops:read', 'quality-ops:export', 'design-dev:read', 'design-dev:export', 'safety-sensitive:read', 'safety-sensitive:export', 'antibribery-sensitive:read', 'antibribery-sensitive:export']::TEXT[]
    WHEN 'CONTRIBUTOR'::"Role" THEN ARRAY['dashboard:read', 'notifications:read', 'documents:read', 'documents:create', 'processes:read', 'risks:read', 'risks:create', 'audits:read', 'audits:create', 'indicators:read', 'indicators:create', 'evidence:read', 'evidence:create', 'records:read', 'records:create', 'actions:read', 'actions:create', 'actions:update', 'nc:read', 'training:read', 'changes:read', 'suppliers:read', 'opportunities:read', 'personnel:read', 'positions:read', 'catalogs:read', 'security-controls:read', 'soa:read', 'risk-treatment:read', 'assets:read', 'assets:create', 'incidents:read', 'incidents:create', 'vulnerabilities:read', 'continuity:read', 'standards:read', 'environment:read', 'environment:create', 'safety:read', 'safety:create', 'integrated:read', 'aims:read', 'aims:create', 'compliance:read', 'speakup:create', 'energy:read', 'energy:create', 'food-safety:read', 'food-safety:create', 'itsm:read', 'itsm:create', 'medical-devices:read', 'medical-devices:create', 'quality-ops:read', 'quality-ops:create', 'design-dev:read', 'design-dev:create']::TEXT[]
    WHEN 'VIEWER'::"Role" THEN ARRAY['dashboard:read', 'notifications:read', 'documents:read', 'processes:read', 'evidence:read', 'records:read', 'risks:read', 'audits:read', 'indicators:read', 'training:read', 'changes:read', 'suppliers:read', 'reporting:read', 'activity:read', 'personnel:read', 'positions:read', 'catalogs:read', 'mgmt-review:read', 'security-controls:read', 'soa:read', 'risk-treatment:read', 'assets:read', 'incidents:read', 'vulnerabilities:read', 'continuity:read', 'standards:read', 'environment:read', 'safety:read', 'integrated:read', 'aims:read', 'compliance:read', 'speakup:create', 'energy:read', 'food-safety:read', 'itsm:read', 'medical-devices:read', 'quality-ops:read', 'design-dev:read']::TEXT[]
    WHEN 'ADMIN'::"Role" THEN ARRAY['dashboard:read', 'notifications:read', 'org:*', 'members:*', 'groups:*', 'documents:*', 'processes:*', 'evidence:*', 'records:*', 'risks:*', 'audits:*', 'audit-program:*', 'nc:*', 'actions:*', 'indicators:*', 'gap:*', 'training:*', 'changes:*', 'suppliers:*', 'opportunities:*', 'integrations:*', 'reporting:*', 'activity:*', 'positions:*', 'personnel:*', 'locations:*', 'catalogs:*', 'mgmt-review:*', 'billing:*', 'security-controls:*', 'soa:*', 'risk-treatment:*', 'assets:*', 'incidents:*', 'vulnerabilities:*', 'continuity:*', 'standards:*', 'environment:*', 'safety:*', 'integrated:*', 'aims:*', 'compliance:*', 'speakup:create', 'energy:*', 'food-safety:*', 'itsm:*', 'medical-devices:*', 'md-sensitive:*', 'quality-ops:*', 'design-dev:*', 'safety-sensitive:*', 'antibribery-sensitive:*']::TEXT[]
    ELSE ARRAY[]::TEXT[]
  END
$$;
