-- Table RLS is now canonical in Prisma migration:
-- prisma/migrations/20260619020000_row_level_security/migration.sql
--
-- This version is intentionally kept as a no-op so existing Supabase migration
-- histories do not diverge. Run `prisma migrate deploy` before Supabase storage
-- migrations.
